pingcap/ossinsight

.github/workflows/deploy.yml
=> support surge.sh

package-lock.json, package.json, src/api/gh.ts, src/api/query.ts, src/components/CommonChart/CommonChart.js, src/components/ThemeAdaptor/index.tsx, src/components/TopList/index.tsx, src/components/WordCloud/index.tsx, src/components/github/Owner/index.tsx, src/components/github/index.ts, src/pages/index.js, tsconfig.json, yarn.lock
=> Add top 20 list in home page

package-lock.json, package.json, src/api/query.ts, src/components/TopList/config.tsx, src/components/TopList/index.module.css, src/components/TopList/index.tsx, src/components/WordCloud/index.tsx, src/components/WordCloud/style.css, src/components/github/Owner/index.tsx, src/pages/index.js, src/pages/index.module.css, yarn.lock
=> WIP better home page

src/components/CompareHeader/CompareHeader.tsx, src/components/CompareHeader/RepoSelector.tsx, src/components/RemoteCards/BasicCard.tsx, src/components/RemoteCards/CompareCard.tsx, src/components/RemoteCards/CompareNumbers.tsx, src/components/RemoteCards/HeatMapChartCard.tsx, src/components/RemoteCards/LineAreaBarChartCard.tsx, src/components/RemoteCards/PieChartCompareCard.tsx, src/components/RemoteCards/compare-numbers.module.css, src/components/RemoteCharts/DebugInfoModel.tsx, src/components/RemoteCharts/hook.ts, src/components/RemoteCharts/theme.ts, src/pages/compare/index.module.css, src/pages/compare/index.tsx
=> update compare page ui

src/components/RemoteCharts/hook.ts
The change in the hook.ts of commit f8ffcc7 will cause the repo selector to crash and history and hourly page not working.
cc: @634750802
=> revert: revert hook.ts changes from f8ffcc7

docs/database/02-realtime.mdx, docs/js-framework/02-realtime.mdx, docs/language/02-realtime.mdx, docs/low-code/02-realtime.mdx, docs/web-framework/02-realtime.mdx
The title is wrong.
cc: @634750802
=> fix: fix the top repo by developers title

docs/database/01-deep-insight-about-oss-database-2021.md, docs/database/02-realtime.mdx, docs/database/03-history.mdx, docs/database/index.md, docs/js-framework/01-deep-insight-into-js-framework-2021.md, docs/js-framework/02-realtime.mdx, docs/js-framework/03-history.mdx, docs/js-framework/index.md, docs/web-framework/01-deep-insight-about-web-framework-2021.md, docs/web-framework/02-realtime.mdx, docs/web-framework/03-history.mdx, docs/web-framework/index.md
update English content about  database, JavaScript framework and web framework part
=> update content part 1

blog/about.md, src/pages/compare/_sections/1-stars-1-numbers.tsx, src/pages/compare/_sections/1-stars-2-history.tsx, src/pages/compare/_sections/1-stars-3-country-area.tsx, src/pages/compare/_sections/1-stars-4-companies.tsx, src/pages/compare/_sections/2-prs-1-numbers.tsx, src/pages/compare/_sections/2-prs-2-history.tsx, src/pages/compare/_sections/2-prs-3-creators.tsx, src/pages/compare/_sections/2-prs-4-country-area.tsx, src/pages/compare/_sections/2-prs-5-companies.tsx, src/pages/compare/_sections/3-issues-1-numbers.tsx, src/pages/compare/_sections/3-issues-2-country-area.tsx, src/pages/compare/_sections/3-issues-3-companies.tsx, src/pages/compare/_sections/4-commits-1-numbers.tsx, src/pages/compare/_sections/4-commits-2-time.tsx
=> content update 420 compare+about

blog/try-it-yourself.md
=> fix: use the us-west-2 region rather than the closest one

src/components/RemoteCharts/queries.ts, src/components/StatusBar/index.module.css, src/components/StatusBar/index.tsx, src/pages/compare/index.tsx, src/theme/CustomPage/index.tsx, src/theme/DocPage/index.js, src/theme/DocPage/styles.module.css
=> feat: add debug bar

docs/js-framework/01-deep-insight-into-js-framework-2021.mdx, docs/language/01-deep-insight-into-programming-languages-2021.mdx, docs/low-code/01-deep-insight-into-lowcode-development-tools-2021.mdx, docs/web-framework/01-deep-insight-about-web-framework-2021.mdx
1. Update page titles
2. Delete front images
=> update insight pages

blog/authors.yml, blog/say-thanks-to-github-robots/index.md
=> blog: add new blog `Say Thanks to GitHub Robots`

.gitmodules
Reverts pingcap/ossinsight#299
=> Revert "merge backend repo"

src/analyze-charts/options/series.ts
=> fix: use location name as id

src/components/CommonChart/CommonChart.js, src/components/ECharts/index.tsx, src/components/InViewContainer/index.tsx, src/components/RealtimeSummary/hooks.ts, src/components/RealtimeSummary/index.tsx, src/components/RemoteCharts/hook.ts, src/dynamic-pages/analyze/Section.tsx, src/dynamic-pages/collections/dimensions.tsx, src/dynamic-pages/collections/hooks/useTabs.tsx, src/dynamic-pages/collections/sections/history-rank.tsx, src/dynamic-pages/collections/sections/history-sort.tsx, src/dynamic-pages/collections/sections/history.tsx, src/dynamic-pages/collections/sections/month-rank.tsx, src/hooks/url-search-state.ts, src/hooks/visibility.ts, src/pages/home/_index.tsx
- add tooltip for realtime summary
- add url search binding for tabs in collections page
- add browser visibility check to prevent api call in background
=> enhancement: optimize ui

.github/workflows/preview.yaml
Try to fix the broken preview workflow.
=> workflow: add preview github action

.github/workflows/deploy.yml
Separate deploy and preview workflow.
cc: @634750802 @sykp241095
=> workflow: fix the deploy workflow

src/theme/CodeBlock/index.js, src/theme/CodeBlock/styles.module.css
=> fix: use native copy api

src/components/TopList/index.tsx
=> fix: disable focus listener

docusaurus.config.js
=> fix a typo

backend/meta/collections/10030.web3.yml
=> collections: add web3 repos collection

src/dynamic-pages/analyze/sections/0-Overview.tsx
=> fix: add background for owner logo

src/dynamic-pages/analyze/sections/1-People.tsx, src/dynamic-pages/analyze/typography.tsx
=> fix: chart title in tabs

src/api/gh.ts, src/dynamic-pages/analyze/index.tsx
=> fix: show 404 when repo not exists in analyze page

src/dynamic-pages/analyze/sections/5-Contributors.tsx
=> fix: contributor dimension selector content

.github/workflows/verify-query.yml
Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
=> workflow: use the default working directory for verify workflow

src/dynamic-pages/collections/sections/history-sort.tsx
=> fix: time formatter

api/app/core/GhExecutor.ts, api/app/server.ts
=> feat: user search support filter by user type

workshop/mini-ossinsight/introduction.md
ossinsiht -> ossinsight
Signed-off-by: Ry Jones <ry@linux.com>
=> Update URL in intro

api/queries/personal-overview/template.sql
**The `actor_id` when merged with PR is not the PR author himself**
=> fix: fix personal loc count

backend/meta/collections/2.open-source-database.yml
Signed-off-by: Xuanwo <github@xuanwo.io>
This PR will add Postgres and Duckdb in open source db collections
=> feat: Add postgres and duckdb in open source db collections

src/css/custom.css, src/pages/analyze-company/_components/Companies.tsx, src/pages/analyze-company/_components/SearchCompany.tsx, src/pages/analyze-company/_components/hooks.tsx, src/pages/analyze-company/index.tsx
https://pingcap-ossinsight-preview-pr-546.surge.sh/analyze-company
=> feat: company analyze page (beta)

src/dynamic-pages/analyze-user/charts/context.ts, src/dynamic-pages/analyze-user/index.tsx
=> fix: show 404 when user not found

src/components/DebugDialog/index.ts, src/components/DebugDialog/useDebugDialog.tsx, src/dynamic-pages/analyze-user/charts/ChartWrapper.tsx, src/dynamic-pages/analyze-user/charts/Common.tsx, src/dynamic-pages/analyze-user/charts/context.ts, src/dynamic-pages/analyze-user/charts/time-distribution/index.tsx, src/dynamic-pages/analyze-user/index.tsx, src/dynamic-pages/analyze-user/sections/0-Overview.tsx, src/dynamic-pages/analyze-user/sections/1-Behaviour.tsx, src/dynamic-pages/analyze-user/sections/2-Star.tsx, src/dynamic-pages/analyze-user/sections/3-Code.tsx, src/dynamic-pages/analyze-user/sections/4-CodeReview.tsx, src/dynamic-pages/analyze-user/sections/5-Issue.tsx, src/dynamic-pages/analyze-user/sections/6-Activities.tsx, src/dynamic-pages/analyze/sections/5-Contributors.tsx
=> fix: charts

backend/meta/collections/10050.open-source-forem-software.yml
Close https://github.com/pingcap/ossinsight/issues/552
=> colllection: add open source forem software collection

plugins/gtag/content-group.js
Hi Jagger @634750802 , I want to track all workshop page's link in a content group, could you review my codes below?
=> tracking：add workshop content group for tracking

api/queries/recent-events-rank-v2/params.json, api/queries/recent-events-rank-v2/template.sql
part of https://github.com/pingcap/ossinsight/issues/612
=> feat: add recent-events-rank-v2 query

README.md, _blog/why-you-should-choose-tidb.mdx, src/dynamic-pages/analyze/sections/3-PullRequests.tsx, src/dynamic-pages/collections/dynamic-trends.tsx, src/dynamic-pages/collections/sections/history-rank.tsx, src/dynamic-pages/collections/sections/history-sort.tsx, src/dynamic-pages/collections/sections/history.tsx, src/dynamic-pages/collections/sections/month-rank.tsx, src/pages/about.md
Signed-off-by: disksing <i@disksing.com>
=> use half-angle parentheses instead of full angle

api/compute-prefetch-enums.ts
Reverts pingcap/ossinsight#638
=> Revert "fix: increment sleep time"

src/dynamic-pages/analyze-user/charts/ChartWrapper.tsx, src/dynamic-pages/analyze-user/sections/0-Overview.tsx, src/dynamic-pages/analyze-user/sections/1-Behaviour.tsx, src/dynamic-pages/analyze-user/sections/2-Star.tsx, src/dynamic-pages/analyze-user/sections/3-Code.tsx, src/dynamic-pages/analyze-user/sections/4-CodeReview.tsx, src/dynamic-pages/analyze-user/sections/5-Issue.tsx, src/dynamic-pages/analyze-user/sections/6-Activities.tsx, src/dynamic-pages/analyze/charts/chart.tsx, src/dynamic-pages/analyze/charts/options/_danger.ts, src/dynamic-pages/analyze/sections/5-Contributors.tsx
=> ui: add loading indicators

backend/meta/collections/10054.monitoring-tools.yml
=> collection: add monitoring tools

backend/lib/tweet_repo.rb
issue: https://twitter.com/MiSTer_Birdybro/status/1554599348238835712
=> only count merged pr

api/queries/analyze-issue-creators-company/template.sql, api/queries/analyze-people-activities-contribution-rank/template.sql, api/queries/analyze-pull-request-creators-company/template.sql, api/queries/analyze-repo-issue-overview/params.json, api/queries/analyze-repo-issue-overview/template.sql, api/queries/analyze-repo-overview/params.json, api/queries/analyze-repo-overview/template.sql, api/queries/analyze-repo-pr-overview/params.json, api/queries/analyze-repo-pr-overview/template.sql, api/queries/analyze-stars-company/params.json, api/queries/analyze-stars-company/template.sql, api/queries/issue-comments-total/template.sql, api/queries/issue-creators-map/template.sql, api/queries/issue-creators-top-50-company/template.sql, api/queries/pull-request-creators-map/template.sql, api/queries/pull-request-creators-top-50-company/template.sql, api/queries/pull-request-reviews-total/template.sql, api/queries/stars-map/template.sql, api/queries/stars-top-50-company/template.sql
=> fix(sql): simpify sqls

backend/meta/collections/10027.testing-tool.yml
MeterSphere Repo: https://github.com/metersphere/metersphere/
Thanks in advance.
=> Add MeterSphere to testing-tool Collection

backend/meta/collections/10051.security-tool.yml
JumpServer Repo: https://github.com/jumpserver/jumpserver
Thanks.
=> Add jumpserver/jumpserver to security-tool

src/dynamic-pages/analyze/charts/summary/Summary.tsx, src/dynamic-pages/analyze/sections/0-Overview.tsx, src/dynamic-pages/analyze/sections/3-PullRequests.tsx, src/dynamic-pages/analyze/sections/4-Issues.tsx
=> feat: combine analyze summary queries

backend/meta/collections/10008.graph-database.yml
Add Memgraph GitHub repo to Graph Database collection.
=> Add Memgraph to Graph Database collection

api/queries/stars-map/template.sql
close https://github.com/pingcap/ossinsight/issues/690
=> fix(sql): fix the repo id in the stars map template sql

backend/meta/collections/10044.modern-data-stack.yml
Add apache/dolphinscheduler to modern data stack collections
=> [Feat] Add apache/dolphinscheduler to modern data stack collections

backend/meta/collections/10056.data-integration.yml
add data integration collection
=> add data integration collection

src/pages/home/_sections/1-collections/Collections.tsx
close https://github.com/pingcap/ossinsight/issues/708
=> ui: add border for avatars

backend/lib/trending_repo_generator.rb, backend/lib/tweet_repo.rb
* weekly stars increment from 200 to 100
* use min(stars_count, stars_incr_count)
=> twitter bot enhance

api/queries/analyze-issue-open-to-closed/template.sql, api/queries/analyze-issue-open-to-first-responded/template.sql, api/queries/analyze-issue-opened-and-closed/template.sql, api/queries/analyze-pull-request-open-to-merged/template.sql
Performance first, so we could treat robot's response as real response (for temp).
=> Tune sql performance

backend/meta/collections/10057.workflow-scheduler.yml
add workflow scheduler collection.
=> Add workflow scheduler collection

docusaurus.config.js, src/components/Footer/index.tsx, src/components/GeneralSearch/index.tsx, src/pages/home/_sections/0-summary/left/GeneralSearchLine.tsx, src/pages/home/_sections/0-summary/right/index.tsx, src/pages/home/_sections/1-collections/Collections.tsx, src/pages/home/_sections/1-collections/index.tsx, src/pages/home/_sections/2-toplistv2/TopListV2.tsx, src/pages/home/_sections/2-toplistv2/index.tsx, src/pages/home/_sections/3-workshop/Workshop.tsx, src/pages/home/_sections/3-workshop/index.tsx
=> docs: update homepage text

src/dynamic-pages/analyze/sections/1-People.tsx
=> enhancement(#699): replace stars-map with analyze-stars-map

src/dynamic-pages/analyze/sections/5-Contributors.tsx
=> feat(#712): add contribution rank type

src/dynamic-pages/analyze/sections/2-Commits.tsx
=> enhancement(#700): add period select for commits time

src/dynamic-pages/analyze/sections/0-Overview.tsx
Close https://github.com/pingcap/ossinsight/issues/696
=> fix(#696): hide texts if no data

src/dynamic-pages/analyze/sections/0-Overview.tsx
=> enhancement(#701): change star-history query

src/components/GeneralSearch/index.tsx
=> fix(#754): add bg for logos in search list

src/components/params/useSelectParam.tsx, src/dynamic-pages/analyze-user/hooks/usePersonal.ts, src/dynamic-pages/analyze-user/sections/1-Behaviour.tsx, src/dynamic-pages/analyze/charts/heatmap/index.tsx, src/dynamic-pages/analyze/sections/2-Commits.tsx
=> enhancement: update chart queries

api/app/core/cache/CacheBuilder.ts, api/app/core/cache/CachedTableCacheProvider.ts, api/app/core/cache/NormalTableCacheProvider.ts
Reverts pingcap/ossinsight#765
=> Revert "feat: make cache db conn as pool"

README.md, docusaurus.config.js, src/components/Footer/index.tsx, src/dynamic-pages/collections/dynamic-trends.tsx, src/dynamic-pages/collections/sections/history-rank.tsx, src/dynamic-pages/collections/sections/history-sort.tsx, src/dynamic-pages/collections/sections/history.tsx, src/dynamic-pages/collections/sections/month-rank.tsx, src/pages/home/_sections/1-collections/index.tsx, src/pages/home/_sections/2-toplistv2/index.tsx, workshop/overview.mdx
Please check the content in workshop overview. @sykp241095
=> docs:update text for collections/workshop/readme

backend/meta/collections/10051.security-tool.yml
Adding a few more tools
there are multiple awesome lists around security tooling i would suggest extracting projects from those list to fill this sheet up.
=> Added a few more security tools

api/app/server.ts, api/index.ts, api/package.json, api/pnpm-lock.yaml, package-lock.json, package.json, src/api/client.ts, src/components/RealtimeSummary/hooks.ts, src/components/RealtimeSummary/index.tsx, src/components/RemoteCharts/hook.ts, src/pages/home/_components/events.tsx, src/pages/home/_sections/0-summary/left/TotalNumber.tsx, src/pages/home/_sections/0-summary/right/Events.tsx
WS Server:
- With Koa
- Port default `3450`
- CORS
- Handle event `query` (part of `/q/xxx`)
WS Client:
- `events-increment?ts=<TIMESTAMP>`
- `events-increment-intervals`
- `events-increment-list`
Close https://github.com/pingcap/ossinsight/issues/611
=> feat: add websocket server & client for events

api/queries/trending-repos/params.json, api/queries/trending-repos/template.sql
part of #776, #777, #778
- Supports filtering in three time ranges ( "last_day", "last_week", "last_month")
- Support the filtering of the primary language of the repository, and currently support more than 30 programming languages.
We calculate the comprehensive score based on the nearest stars and forks of the repository:
*Stars score*: 
- Calculate the score of each star according to the time of the star, the closer to the current time, the higher the score gets, the score range is between 2-5.
- Then sum the scores of all stars to get the total score obtained from the stars for the repository.
- If the number of stargazers in a repo is significantly less than the number of stars, then its *Stars score* will be 0.
*Forks Score*: 
- Calculate the score of each fork according to the time …
=> feat: add trending repos query

api/app/server.ts, api/index.ts
=> fix: websocket reuse db conn pool

backend/meta/collections/2.open-source-database.yml
Changes proposed in this pull request:
- Add ShardingSphere to Open Source Database collection
=> Add ShardingSphere to Open Source Database collection

api/app/utils/github.ts, api/scripts/sync-repos/index.ts, api/scripts/sync-repos/loader.ts, api/scripts/sync-repos/syncer.ts, api/scripts/sync-repos/worker.ts, api/scripts/sync-users/index.ts
=> feat: add sync forks repos command

api/app/utils/db.ts, api/scripts/sync-repos/index.ts, api/scripts/sync-repos/puller.ts, api/scripts/sync-repos/syncer.ts
part of #807
Also fix the error caused by disabled repo.
=> feat: support pull repos by limit

api/scripts/sync-repos/index.ts, api/scripts/sync-repos/puller.ts, api/scripts/sync-repos/syncer.ts
=> feat: support sync inc repos

api/allowed-origins.yaml, api/app/core/BatchLoader.ts, api/app/metrics.ts, api/app/middlewares/measureRequests.ts, api/app/origins.ts, api/app/server.ts, api/app/services/StatsService.ts, api/index.ts, api/scripts/sync-repos/worker.ts, api/scripts/sync-users/index.ts
=> feat: add API stats 

src/dynamic-pages/stats/components/LiveSql.tsx
=> fix: ignore error on safari

api/.env.template, api/app/utils/env.ts, api/app/utils/playground.ts, api/index.ts
=> config(playground): use env parameterize playground session limits

src/pages/home/_sections/2-toplistv2/TopListV2.tsx
=> feat(trending): add external link in trending list

backend/meta/collections/1.static-site-generator.yml
I want to suggest Cecil, a static site generator powered by PHP.
=> feat: add Cecil to SSG collection

src/dynamic-pages/analyze/sections/0-Overview.tsx, types/ossinsight.d.ts
=> feat(analyze-page): add repo description

api/app/utils/playground.ts, src/dynamic-pages/analyze/sections/6-SQLPlayground.tsx
- Remove auto adding `WHERE` clause, use Error message
- Remove auto formatting, add `Format` button
- Remove placeholder with default input value
- Only check `WHERE` clause if `FROM` existing
- Remove reutrned SQL
- `Explain` now have prettier output
=> [fix] refine sql playground sep30

backend/meta/collections/10027.testing-tool.yml
robot framework belongs in testing tools
=> added robot framework

api/app/core/GenericJobWorkerPool.ts, api/scripts/sync-repos/index.ts, api/scripts/sync-repos/loader.ts, api/scripts/sync-repos/syncer.ts, api/scripts/sync-users/index.ts, api/scripts/sync-users/loader.ts, api/scripts/sync-users/syncer.ts
Also sync-repos support setting filter as `created` / `pushed`
=> refactor: use generic job workers

api/app/core/BatchLoader.ts, api/scripts/sync-repos/loader.ts, api/scripts/sync-repos/syncer.ts, api/scripts/sync-users/loader.ts
=> fix: fix sync repos batch insert error

backend/meta/collections/10010.artificial-intelligence.yml
=> add towhee into AI category

backend/meta/collections/10027.testing-tool.yml
added playwright, selenide, webdriverio to testing tools collection
=> added playwright selenide webdriverio to testing tools collection

api/queries/trending-repos/template.sql
=> fix: remove ifnull func in trending repos

src/dynamic-pages/analyze/charts/common-duration/index.ts, src/dynamic-pages/analyze/charts/issue/index.ts, src/dynamic-pages/analyze/charts/loc/index.ts, src/dynamic-pages/analyze/charts/options/utils/axis.ts, src/dynamic-pages/analyze/charts/pr/index.ts, src/dynamic-pages/analyze/charts/push-and-commits/index.ts, src/dynamic-pages/analyze/charts/utils.ts
=> feat(analyze-ui): align y-axis while comparing

api/queries/analyze-issue-open-to-closed/template.sql, api/queries/analyze-people-activities-contribution-rank/template.sql, api/queries/analyze-people-code-contribution-rank/template.sql, api/queries/analyze-people-code-pr-contribution-rank/template.sql, api/queries/analyze-people-code-review-comments-contribution-rank/template.sql, api/queries/analyze-people-code-review-prs-contribution-rank/template.sql, api/queries/analyze-people-code-review-submits-contribution-rank/template.sql, api/queries/analyze-people-issue-close-contribution-rank/template.sql, api/queries/analyze-people-issue-comment-contribution-rank/template.sql, api/queries/analyze-people-issue-contribution-rank/template.sql, api/queries/analyze-stars-history/template.sql, api/queries/collection-issues-month-rank/template.sql, api/queries/collection-pull-requests-month-rank/template.sql, api/queries/collection-stars-month-rank/template.sql, api/queries/personal-languages/template.sql, api/queries/personal-overview/template.sql
=> fix: improve sqls with actor login and event month

web/src/dynamic-pages/analyze/sections/99-SQLPlayground.tsx
=> fix: display repo id in placeholder

 .gitpod.Dockerfile, .gitpod.yaml
part of https://github.com/pingcap/ossinsight/issues/971
=> config: add gitpod config

etl/Gemfile.lock, etl/config/database.yml
https://github.com/pingcap/ossinsight/issues/970
=> tidb ssl mode

packages/api-server/src/plugins/runner/query/index.ts
Reverts pingcap/ossinsight#995
=> Revert "fix: fix query runner dep"

.husky/pre-push, web/src/components/BrowserHash/index.tsx, web/src/components/Experimental/index.ts, web/src/components/milestone/MilestoneLite.tsx, web/src/components/milestone/MilestoneTimeline.tsx, web/src/dynamic-pages/analyze/index.tsx, web/src/dynamic-pages/analyze/sections/0-Overview.tsx, web/src/pages/2022/index.tsx
=> fix(web): fix analyze ui

web/docusaurus.config.js
=> fix: web config

web/src/dynamic-pages/collections/components/EditCollection.tsx, web/src/dynamic-pages/collections/layout.tsx, web/src/dynamic-pages/collections/sections/typograpy.tsx, web/src/pages/collections/_components/filters.tsx, web/src/pages/collections/index.tsx
close #964 
Also add `edit this collections` button https://github.com/pingcap/ossinsight/issues/964#issuecomment-1326182806
=> ui(#964): refine collections page

CONTRIBUTING.md, README.md
=> [others]Updata readme

CONTRIBUTING.md
=> [fix]Update the urls

packages/api-server/src/services/bot-service/index.ts
=> api: question to sql support convert repo name to repo id

packages/api-server/__tests__/helpers/app.ts, packages/api-server/src/app.ts, packages/api-server/src/env.ts, packages/api-server/src/plugins/auth/github.ts, packages/api-server/src/routes/bot/questionToSQL/index.ts, packages/api-server/src/services/bot-service/index.ts, packages/api-server/src/services/playground-service/index.ts
=> bot: add limitation for the question to SQL API

packages/api-server/__tests__/helpers/app.ts, packages/api-server/src/app.ts, packages/api-server/src/env.ts, packages/api-server/src/routes/bot/questionToSQL/index.ts
=> bot: add trusted logins config for question2sql

.devcontainer/devcontainer.json, dev.Dockerfile
=> docker: build dev container docker image

.github/workflows/dockerhub.yml, docker-compose.yml
=> docker: rename docker images

packages/api-server/src/plugins/services/bot-service/index.ts
=> bot: remove the repo_name to repo_id hint

packages/api-server/src/plugins/services/bot-service/index.ts
=> bot: add today hint

etl/meta/collections/10003.low-code-development-tool.yml
I added some tools to collection.
- https://chiselstrike.com/
- https://grafbase.com/
- https://oss.platformatic.dev/
=> collection: add low code dev tools to collections

packages/api-server/src/plugins/services/playground-service/index.ts, packages/api-server/src/routes/bot/questionToSQL/index.ts
=> bot: add rate limit info to header

packages/api-server/src/plugins/cors/index.ts
=> cors: allow headers for generate sql rate limit

web/docs/api/overview.md
=> api: update the api overview

packages/api-server/__tests__/app.ts, packages/api-server/src/plugins/cors/index.ts, packages/api-server/src/routes/bot/questionToSQL/index.ts
=> api: fix question api

.husky/pre-push, packages/api-server/src/routes/bot/questionToSQL/index.ts, web/src/api/client.ts, web/src/api/core.ts, web/src/dynamic-pages/analyze/playground/PlaygroundContent.tsx, web/src/dynamic-pages/analyze/playground/QuestionField.tsx, web/src/dynamic-pages/analyze/playground/hooks.ts
=> web: add ai question quota

etl/README.md, etl/app/models/item.rb, etl/config/environments/development.rb, etl/config/initializers/fetch_item.rb, etl/config/initializers/hn_realtime.rb, etl/db/migrate/20221218164010_init_hackernews_db.rb
* Add full Hacker News datasets
* Fetching Hacker News data realtime
```sql
test> desc hackernews.items;
+---------------+---------------+------+-----+---------------------+-------+
| Field         | Type          | Null | Key | Default             | Extra |
+---------------+---------------+------+-----+---------------------+-------+
| id            | bigint(20)    | NO   | PRI | <null>              |       |
| title         | varchar(198)  | YES  |     | <null>              |       |
| url           | varchar(6598) | YES  |     | <null>              |       |
| text          | text          | YES  |     | <null>              |       |
| type          | varchar(8)    | NO   |     | story               |       |
| by            | varchar(15)   | NO   |     |                     |       |
| …
```
=> fetch hackernews items realtime

etl/config/initializers/fetch_item.rb, etl/db/migrate/20221219004928_add_parts_and_kids_for_hackernews.rb
=> add kids & parts column for HN

pnpm-workspace.yaml
=> workspace: add legecy api-server to pnpm-workspace.yaml

web/package-lock.json, web/package.json, web/src/components/Footer/index.tsx
=> web: add a github star button in the footer

etl/lib/tweet_collection.rb
=> fix irregular collection name mapping

etl/lib/tweet_repo.rb
=> use github default card #1046

etl/app/models/github_event.rb, etl/app/models/hn_item.rb, etl/app/models/hn_user.rb, etl/app/models/mention_log.rb, etl/config/environments/development.rb, etl/config/initializers/hn_fetch_item.rb, etl/config/initializers/hn_fetch_user.rb, etl/config/initializers/hn_realtime.rb, etl/db/migrate/20221220182157_create_hn_users.rb, etl/test/fixtures/github_events.yml, etl/test/fixtures/mention_logs.yml, etl/test/models/github_event_test.rb, etl/test/models/mention_log_test.rb
=> ETL: add hackernews users

etl/config/initializers/hn_fetch_user.rb, etl/config/initializers/hn_realtime.rb, etl/config/initializers/hn_update.rb
=> ETL: update recent changed items & users

web/docs/api/overview.md
=> chore(docs) fix pull request link

web/docs/workshop/overview.mdx
=> docs: Add Hacker News Insight link

web/src/dynamic-pages/analyze/sections/0-Overview.tsx
I fixed the title string overflow if the long word on sp.
|before|after|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11070996/209451742-75e82717-2242-4c50-9dd0-6bdf808e657f.png) | ![image](https://user-images.githubusercontent.com/11070996/209451745-b63be97d-3ca7-4958-b4e3-c4baa6fa4bb4.png) |
=> chore(docs) fix title string overflow if long word

CONTRIBUTING.md, README.md, web/docs/about.md
Issue Number: close #1062 
Problem Summary: Some grammar and punctuation mistakes exist in `README.md`, `CONTRIBUTING.md`
- Updates intro to OSS Insight, wording
- Fix typo, grammar, punctuation
=> readme, web: update descriptions, fix typo and punctuation

etl/meta/collections/2.open-source-database.yml
It is a trivial PR just to add an item to the open-source database collection. Let me know If I need to create an issue.
I'd like to add CUBRID/cubrid to open source database collection.
=> config: add CUBRID/cubrid repo to open source database collection

etl/meta/collections/10069.optimization-solvers.yml
Adding optimization-solvers collection.
=> config: adding optimization-solvers collection

etl/lib/tweet_repo.rb, web/src/dynamic-pages/analyze/sections/0-Overview.tsx
Added a `#overview-main` wrapper element for screenshot
Issue Number: related #1046
=> web(analyze): add a wrapper element to analyze overview section

web/src/api/explorer.ts, web/src/hooks/force-update.ts, web/src/hooks/operation.ts, web/src/pages/explore/_components/Execution.tsx, web/src/pages/explore/_components/Search.tsx, web/src/pages/explore/_components/charts/TableChart.tsx, web/src/pages/explore/_components/charts/index.tsx, web/src/pages/explore/index.tsx
=> web(explore): optimize ui

configs/queries/personal-contribution-time-distribution/params.json, configs/queries/personal-contribution-trends/params.json, configs/queries/personal-contribution-trends/template.sql, configs/queries/personal-contributions-for-repos/params.json, configs/queries/personal-issues-history/params.json, configs/queries/personal-issues-history/template.sql, configs/queries/personal-languages/params.json, configs/queries/personal-languages/template.sql, configs/queries/personal-overview/params.json, configs/queries/personal-overview/template.sql, configs/queries/personal-pull-request-action-history/params.json, configs/queries/personal-pull-request-action-history/template.sql, configs/queries/personal-pull-request-code-changes-history/params.json, configs/queries/personal-pull-request-code-changes-history/template.sql, configs/queries/personal-pull-request-reviews-history/params.json, configs/queries/personal-pull-request-reviews-history/template.sql, configs/queries/personal-pull-request-size-history/params.json, configs/queries/personal-pull-request-size-history/template.sql, configs/queries/personal-pushes-and-commits/params.json, configs/queries/personal-pushes-and-commits/template.sql, configs/queries/personal-star-history/params.json, configs/queries/personal-star-history/template.sql
=> api: add 2022 personal analyze period

packages/api-server/__tests__/plugins/services/bot-service/__snapshots__/template.ts.snap, packages/api-server/src/app.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateChartPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateSQLPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/QueryPlaygroundPromptTemplate.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: refine the chart prompt and fix the tx commit problem

packages/api-server/__tests__/plugins/services/bot-service/__snapshots__/template.ts.snap, packages/api-server/src/plugins/services/bot-service/template/GenerateChartPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts
=> bot-service: improve the chart generate prompt

packages/api-server/__tests__/plugins/services/bot-service/__snapshots__/template.ts.snap, packages/api-server/src/plugins/services/bot-service/template/GenerateChartPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/QueryPlaygroundPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> bot-service: adjust the prompt of sql generate

packages/api-server/__tests__/plugins/services/bot-service/__snapshots__/template.ts.snap, packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateChartPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateQuestionsPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
- fix the error record bug
- improve the error log
- set topP to 1
=> explorer: fix the error records and improve error log

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> explorer: improve sql generate prompt

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/index.ts, packages/api-server/src/routes/explorer/questions/index.ts
=> explorer: wrap the error message

packages/api-server/src/routes/explorer/questions/_questionId/index.ts
=> explorer: fix the empty response when question has error

web/blog/authors.yml, web/blog/chat2query-tutorials/index.md
=> Add Chat2Query tutorials

web/src/pages/explore/_components/Faq.tsx, web/src/pages/explore/index.tsx
=> web(explorer): update faq

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateQuestionsPromptTemplate.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: improve question generate prompt

web/src/pages/explore/_components/Execution.tsx, web/src/pages/explore/_components/Faq.tsx
=> web(explorer): fix link and typo

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
Prompt ai to use window function if necessary.
=> ai(prompt): use window function if necessary

web/src/components/LoginRequired.tsx, web/src/components/milestone/SubscribeButton.tsx, web/src/context/user.tsx, web/src/hooks/operation.ts, web/src/pages/explore/_components/useQuestion.tsx, web/src/pages/subscriptions/index.tsx, web/src/theme/NavbarItem/LoginItem.tsx
=> auth: use loginWithPopup instead of loginWithRedirect

web/package-lock.json, web/package.json
=> web: update typescript to v4.9

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts, packages/api-server/src/routes/explorer/questions/index.ts
=> fix: fix cache invalid bug

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateSummaryPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts, packages/api-server/src/routes/explorer/questions/_questionId/chart/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/feedback/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/summary/index.ts
add summary API: `/explorer/questions/{question_id}/summary`
=> explorer: add summary API and simplify prompts

packages/api-server/src/plugins/services/explorer-service/index.ts
=> fix: state convert running -> summarizing -> success

packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: fix the chart check bug

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> ai(prompt): add star history back but simplier than before

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/job-server/src/app.ts, packages/job-server/src/env.ts, packages/job-server/src/plugins/services/explorer-service.ts
=> job-serever: add timeout for query

packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: add question id for recommend questions

packages/api-server/src/plugins/services/bot-service/template/GenerateSummaryPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: save result before summary

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> explorer: improve prompts, god may not be good at writing sql

packages/api-server/package.json, packages/api-server/src/app.ts, pnpm-lock.yaml
=> Feat add etag for api server

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> ai(prompt): make prompt closer to sql generator

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> prompt: make the chart options right

web/src/pages/explore/_components/ExploreGlobalAds.tsx, web/src/pages/explore/_components/Side.tsx, web/src/pages/explore/_components/SummaryCard.tsx
=> web(explore): update card text and insight card title

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/index.ts
=> explorer: allow new question ignore cache

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> prompt: improve chart generate prompt

packages/api-server/src/app.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/index.ts, packages/api-server/src/utils/error.ts
=> explorer: add minutes to error payload

packages/api-server/src/plugins/services/bot-service/template/GenerateSummaryPromptTemplate.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: reduce the probability of summary generating

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts
=> explorer: refine the question feedback type

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> Remove field is_fork to help OpenAI to choose the right field

web/src/pages/home/_sections/0-summary/left/FooterLine.tsx
=> ui(home): rm useless wording

web/src/pages/explore/_components/Header.tsx, web/src/pages/explore/_components/Recommends.tsx, web/src/pages/explore/_components/Search.tsx
=> web(explore):update placeholder

etl/meta/collections/10056.data-integration.yml
Add [ververica/flink-cdc-connectors](github.com/ververica/flink-cdc-connectors) repo to Data Integration collections
=> config: add ververica/flink-cdc-connectors repo to Data Integration collections

web/src/pages/explore/_components/charts/NumberCard.tsx
=> web: add fallback label for number card

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> ai(prompt): remove unused `size` column

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> fix: add default value for datetime and remove NumberCard's label

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/feedback/cancel/index.ts
=> explorer: support cancel question feedback

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> explorer: improve answer prompt

web/src/hooks/url-search-state.ts
=> web: fix url params state

etl/meta/collections/10051.security-tool.yml
Adding matanolabs/matano repository to open source Security tools collection
.
=> config: add matanolabs/matano repo to open source security tools collection

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> ai(prompt): use `line break` instead of `breaklines`

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
Issue Number: close https://github.com/pingcap/ossinsight/issues/1185
=> ai(prompt): fix gr.country_code

README.md
=> Add Data Explorer to README

web/docusaurus.config.js, web/src/components/TiDBCloudLink/context.tsx, web/src/components/TiDBCloudLink/index.tsx, web/src/pages/explore/_components/Faq.tsx, web/src/pages/explore/_components/Questions.tsx, web/src/pages/explore/_components/ResultSection.tsx, web/src/pages/explore/_components/Side.tsx, web/src/pages/explore/index.tsx, web/src/theme/Layout/index.tsx, web/src/utils/value.ts
=> WIP web: add tidbcloud trial link

web/src/pages/explore/_components/Faq.tsx
=> web(explore): change faq position

etl/meta/collections/10056.data-integration.yml
config: add apache/inlong & bytedance/bitsail to Data Integration collections
=> config: add apache/inlong & bytedance/bitsail to Data Integration collections

packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/recommend/index.ts, packages/api-server/src/routes/explorer/tags/index.ts
=> feat: get recommended questions by tag

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> prompt: clearer sql template description

packages/api-server/src/routes/explorer/questions/recommend/index.ts
=> explorer: recommended questions's n up to 100

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
https://ossinsight.io/explore/?id=9a330e72-85ce-4d9b-996d-0d802083e923
=> ai(prompt): remove questions, add prompt for push event

packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: allow ai generated questions to be empty

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
AI lost sometimes. I add this context to help AI to focus on github dataset.
=> Add specific context about github.

etl/meta/collections/10051.security-tool.yml
config: add chipsec/chipsec repo to security tool collection
=> config: add chipsec/chipsec repo to security tool collection

etl/meta/collections/10071.ansible-devtools.yml
=> config: add ansible devtools collection

etl/lib/trending_repo_generator.rb
=> ETL: add blacklist repo for tweet bot

etl/lib/tweet_repo.rb
=> ETL: add chatgpt hashtag if repo matched

etl/config/initializers/hn_update.rb, etl/lib/tweet_repo.rb
=> ETL: slow down hackernews users update

web/src/api/explorer.ts, web/src/pages/explore/_components/Questions.tsx, web/src/pages/explore/_components/Search.tsx, web/src/pages/explore/_components/useQuestion.tsx
Create without cache `option`/`alt` + `Enter`
=> web(explore): support create without cache

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts, packages/api-server/src/utils/error.ts
=> explorer: add error type

web/src/pages/explore/_components/Search.tsx, web/src/pages/explore/_components/Section.tsx, web/src/pages/explore/_components/SqlSection.tsx
=> web(explore): optimize prompts

etl/lib/fill_watch_event.rb
Fill missing watch events for repo
=> ETL: fill missing watch events

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts
=> explorer: add combined title field

packages/api-server/src/plugins/stats.ts
=> stats: record real IP

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: remain the json parer error message

web/src/pages/explore/_components/ExploreGlobalAds.tsx
=> web(explorer): update global ads

web/src/theme/NavbarItem/useResponsiveAuth0.tsx
=> [web] customize auth0 popup style

web/src/pages/explore/_components/ExploreGlobalAds.tsx
=> fix: update layout

etl/meta/collections/10072.business-management.yml
Problem Summary: Lot of frameworks and libraries but I've found no collection that is related to business management software like invoicing and bookkeeping.
=> ETL: add new 10072.business-management.yml collection

web/src/pages/explore/_components/charts/index.tsx, web/src/pages/explore/_components/charts/utils.ts
=> web(explore): allow data with nullable fields in charts

web/docs/about.md, web/src/pages/explore/_components/AdsSection/OurData.tsx, web/src/pages/explore/_components/ExploreGlobalAds.tsx, web/src/pages/explore/_components/Faq.tsx, web/src/pages/explore/_components/Header.tsx, web/src/pages/explore/_components/ResultSection/ResultSection.tsx, web/src/pages/explore/index.tsx
=> web(explorer): change explorer name

packages/api-server/package.json, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, pnpm-lock.yaml
=> explorer: support stream JSON

web/src/pages/explore/_components/SqlSection/ErrorMessage.tsx
=> web(explore): move error detail under the btn

web/src/pages/explore/_components/ResultSection/ResultSection.tsx
Updated `report an issue` link to autofill question info.
=> web(explore): update issue template

web/src/pages/explore/_components/charts/NumberCard.tsx
=> web(explore): single number card support multiple values

packages/api-server/package.json, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, pnpm-lock.yaml
Issue Number: close https://github.com/pingcap/ossinsight/issues/1244
=> fix: upgrade node-sql-parser to support CURRENT_DATE without parentheses

web/src/pages/explore/_components/SqlSection/AIMessages.tsx, web/src/pages/explore/_components/useQuestion.tsx
related #1271 
AI prompts transition behavior is different between new question and executed question.
=> web(explore): adapt stream json

packages/api-server/package.json, pnpm-lock.yaml
=> explorer: upgrade node-sql-parser to 4.6.5

api/scripts/calc-hot-collections/index.ts
=> calc-hot-collecton: add select 1 when connect to db

packages/api-server/__tests__/helpers/app.ts, packages/api-server/src/app.ts, packages/api-server/src/env.ts, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> explorer: support config if answer in stream

packages/api-server/package.json, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, pnpm-lock.yaml
=> explorer: repair the wrong json generated by AI

etl/lib/trending_repo_generator.rb
=> ETL: sync blacklist for tweet bot

etl/meta/collections/10033.identity-server.yml
Add zitadel to identity server collection
=> config: add zitadel to identity server collection

web/src/components/milestone/SubscribeButton.tsx, web/src/context/user.tsx, web/src/dynamic-pages/analyze/playground/PlaygroundContent.tsx, web/src/dynamic-pages/analyze/playground/hooks.ts, web/src/hooks/operation.ts, web/src/pages/explore/_components/Feedback.tsx, web/src/pages/explore/_components/Search.tsx, web/src/pages/explore/_components/useQuestion.tsx, web/src/pages/subscriptions/index.tsx, web/src/theme/NavbarItem/useResponsiveAuth0.tsx, web/src/utils/ga.ts
=> web: run action instantly after login

etl/meta/collections/10051.security-tool.yml, etl/meta/collections/10063.kubernetes-tooling.yml
Signed-off-by: Jim Bugwadia <jim@nirmata.com>
```
config: add kyverno/kyverno repo to security and Kubernetes tools
```
=> add kyverno/kyverno to security and Kubernetes tools

etl/meta/collections/10053.configuration-management-tools.yml
=> [Configuration Management] CNCF project Meshery added

packages/api-server/src/plugins/services/explorer-service/index.ts
Part of https://github.com/pingcap/ossinsight/issues/1295
Don't forget to change the length of VARCHAR in db.
=> explorer: increase max length of question to 512

packages/api-server/src/plugins/services/bot-service/index.ts
=> explorer: fix name mapping of answer

web/src/pages/explore/_components/ChatMessages/ChatMessages.tsx, web/src/pages/explore/_components/ChatMessages/hook.ts, web/src/pages/explore/_components/ChatMessages/index.ts, web/src/pages/explore/_components/SqlSection/AIMessages.tsx, web/src/pages/explore/_components/SqlSection/AIMessagesV2.tsx, web/src/pages/explore/_components/SqlSection/CopyButton.tsx, web/src/pages/explore/_components/SqlSection/Header.tsx, web/src/pages/explore/_components/SqlSection/styled.ts, web/src/pages/explore/_components/SqlSection/utils.ts, web/src/pages/explore/_components/useQuestion.tsx
=> web(explore): display ai messages in realtime

etl/meta/collections/10063.kubernetes-tooling.yml
Missing [Helm](https://helm.sh/) from the list of K8s tools is a big oversight. 
=> Add helm/helm to kubernetes-tooling.yml

etl/meta/collections/10010.artificial-intelligence.yml
=> Add seldon to artificial-intelligence.yml

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts, packages/api-server/src/utils/error.ts
Issue Number: close #1308, close #1285
=> explorer: improve error handle

web/src/api/explorer.ts, web/src/pages/explore/_components/SqlSection/AIMessagesV2.tsx, web/src/pages/explore/_components/SqlSection/styled.ts, web/src/pages/explore/_components/useQuestion.tsx
=> web(explore): add sql ai prompts

web/src/pages/explore/_components/charts/TableChart.tsx
=> web(explore): align table content to the center in chart results.

api/scripts/calc-hot-collections/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/recommend/cancel/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/recommend/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/tags/index.ts, packages/api-server/src/routes/explorer/tags/index.ts, packages/api-server/src/utils/error.ts
Issue Number: close #1338
Add API for admin:
- POST: `/explorer/questions/{question_id}/recommend`
- POST: `/explorer/questions/{question_id}/recommend/cancel`
- GET: `/explorer/questions/{question_id}/tags`
- POST: `/explorer/questions/{question_id}/tags` (Update question tags)
```json
{
"tagIds": [1]
}
```
=> explorer: add recommend question API

web/src/api/explorer.ts, web/src/pages/explore/_components/ExploreMain.tsx, web/src/pages/explore/_components/QuestionSettings.tsx, web/src/pages/explore/_components/useQuestion.tsx
=> web(explore): add settings dialog

packages/api-server/src/routes/explorer/questions/_questionId/tags/index.ts
=> explorer: use empty array as tagIds' default value

api/queries/pull-requests-history/template.sql
=> query: update pull-requests-history query

configs/queries/live-time-top-developers-by-prs-daily/template.sql, configs/queries/live-time-top-repos-by-prs-daily/template.sql
Issue Number: close https://github.com/pingcap/ossinsight/issues/1188
As @fly2F suggested, we adjusted the calculation method of Active Repos and Active Developers on [the real-time contribution page](https://live.ossinsight.io).
We add the following requirements for Top Active Repos:
- The repository stars > 5
- The number of developers who trigger PR events > 5
Add the following requirements for TOP Active Developers:
- Exclude robots
- Followers > 5
=> query: improve live queries

etl/meta/collections/2.open-source-database.yml
Adds greptimedb to open source database collection: https://github.com/GreptimeTeam/greptimedb
Thanks.
=> config: adds greptimedb to open source database collection

etl/meta/collections/10063.kubernetes-tooling.yml
=> Remove duplicate on kubernetes tooling collection

etl/lib/trending_repo_generator.rb
=> ETL: add more trending repo blacklist

web/src/pages/explore/_components/SqlSection/ErrorMessage.tsx, web/src/pages/explore/_components/errorOverride.ts
=> web(explore): spec repo error

etl/meta/collections/10020.cicd.yml
There's a new flux in town.
Issue Number: close #1364
Added flux2, since it's the new and improved flux.
=> config: add flux2 to CICD collection

etl/meta/collections/10020.cicd.yml
=> Add argo rollouts to CICD collection

etl/meta/collections/10052.golang-orm.yml
=> beeorm.io orm

packages/api-server/src/core/executor/query-executor/TiDBQueryExecutor.ts
Issue Number: fix the bug introduced in #1369
=> api-server: release conn for shadow cluster

etl/meta/collections/10016.search-engine.yml
=> ETL: add mosuka/bayard to search engine collection

packages/api-server/package.json, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, pnpm-lock.yaml
=> data-explorer: use openai chat API to answer question

web/docusaurus.config.js
ghtorrent is broken: http://ghtorrent.org/
=> docs: rm unused resource

web/docusaurus.config.js
=> docs: add announcement

web/docusaurus.config.js
=> config: enhance the announcement bar

etl/meta/collections/10007.time-series-database.yml, etl/meta/collections/10008.graph-database.yml, etl/meta/collections/10044.modern-data-stack.yml
- Add surrealdb/surrealdb repo to graph database collection
- Add surrealdb/surrealdb repo to time series database collection
- Add surrealdb/surrealdb repo to modern data stack collection
=> Add `surrealdb/surrealdb` to additional database categories

configs/queries/trending-repos/template.sql
Issue Number: part of https://github.com/pingcap/ossinsight/issues/1394
=> query: fix trending repos query

packages/api-server/src/app.ts, packages/api-server/src/env.ts, packages/api-server/src/plugins/config/context-provider.ts, packages/api-server/src/plugins/config/embedding-context-provider.ts, packages/api-server/src/plugins/config/prompt-template-manager.ts, packages/api-server/src/plugins/services/bot-service/index.ts
- add a context provider mechanism to expand the context passed to prompt-template-manager
- implement EmbeddingContextProvider which calls the embedding service to fetch related context
=> api: support dynamic prompt with embedding search

packages/api-server/src/env.ts, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
=> bot-service: add default value for prompt template

etl/meta/collections/10075.chatgpt-alternatives.yml
=> ETL: add chatgpt alternatives collection

etl/meta/collections/10075.chatgpt-alternatives.yml, etl/meta/collections/10076.llm-tools.yml
=> ETL: add LLM tool collection

etl/meta/collections/10075.chatgpt-alternatives.yml, etl/meta/collections/10076.llm-tools.yml, etl/meta/collections/10077.vector-search-engine.yml
=> ETL: Vector search engine collection

etl/meta/collections/10075.chatgpt-alternatives.yml, etl/meta/collections/10076.llm-tools.yml, etl/meta/collections/10077.vector-search-engine.yml, etl/meta/collections/10078.chatgpt-apps.yml
=> ETL: Add Chatgpt apps collection

packages/api-server/src/core/executor/query-executor/TiDBQueryExecutor.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/job-server/src/app.ts, packages/job-server/src/env.ts, packages/job-server/src/plugins/services/explorer-service.ts
=> data-explorer: data explorer query traffic to shadow cluster

etl/meta/collections/10051.security-tool.yml
Add CloudQuery to the tool listing!  
CloudQuery is an open source high performance data integration platform used for many security and compliance use cases including sourcing information from cloud providers such as AWS, GCP, Azure to do many open source security tooling (CSPMs, Attack Surface Management, etc).
https://cloudquery.io/
=> config: Add cloudquery/cloudquery to security tool listing

etl/meta/collections/10075.chatgpt-alternatives.yml
=> ELT: add nomic-ai/gpt4all to ChatGPT alternative collection

packages/api-server/__tests__/plugins/services/stats-service.ts, packages/api-server/src/core/cache/provider/NormalTableCacheProvider.ts, packages/api-server/src/plugins/services/stats-service/index.ts
=> fix: avoid write traffics to shadow

legacy/api/app/core/cache/CachedTableCacheProvider.ts, legacy/api/app/core/cache/NormalTableCacheProvider.ts
=> fix: ignore write cache

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> data-explorer: refactor the prepare question func

etl/meta/collections/10027.testing-tool.yml
Add [Ddosify](https://github.com/ddosify/ddosify) load testing tool to testing tool collection.
=> config: Add ddosify load testing tool to testing-tool collection

etl/meta/collections/10066.virtual-reality.yml
=> Config: add Overte to virtual-reality collection 

packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/plugins/services/explorer-service/index.ts
=> data-explorer: add log for answer field update

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts, packages/api-server/src/routes/explorer/questions/index.ts
=> data-explorer: refactor update quetsion func

packages/api-server/src/plugins/services/bot-service/index.ts
=> data-explorer: fix null options problem

etl/meta/collections/10024.programming-language.yml
Add:
- https://github.com/flix/flix
- https://github.com/koka-lang/koka
- https://github.com/effekt-lang/effekt
=> ETL: add Flix, Koka, and Effekt programming languages

etl/meta/collections/10051.security-tool.yml
Extending security tools collection by adding `Akto`. [Akto](https://akto.io) is an open source API Security solution which provides continuous API inventory and API testing.
=> config: added Akto to the security tools collection

packages/api-server/src/core/cache/Cache.ts, packages/api-server/src/core/cache/provider/NormalTableCacheProvider.ts, packages/api-server/src/scripts/prefetch/JobScheduler.ts
=> prefetch: fix cache not work problem

packages/api-server/src/core/executor/query-executor/TiDBQueryExecutor.ts
=> fix: query API should return field type

web/src/dynamic-pages/analyze-user/sections/0-Overview.tsx, web/src/dynamic-pages/analyze/sections/6-Contributors.tsx
=> web: fix percentage format

etl/meta/collections/10027.testing-tool.yml
Add [Puppeteer](https://github.com/puppeteer/puppeteer) testing tool to testing tool collection.
=> ETL: Add Puppeteer testing tool to testing-tool collection

etl/meta/collections/10063.kubernetes-tooling.yml
=> Add kubernetes resource recommender (krr) to kubernetes tooling

etl/meta/collections/10024.programming-language.yml
`denoland/deno` missing as "programming language"
Issue Number: N/A
Add `denoland/deno` as "programming language"
=> ETL: add denoland/deno

web/src/dynamic-pages/analyze/playground/PlaygroundContent.tsx, web/src/pages/explore/_components/Faq.tsx
=> web: fix the wrong desc

etl/meta/collections/10063.kubernetes-tooling.yml
=> Add kwok to kubernetes tools

etl/meta/collections/10035.paas.yml, etl/meta/collections/10063.kubernetes-tooling.yml
Add berops/claudie to kubernetes-tooling and paas collections.
=> config: add Claudie to paas and kubernetes-tooling collections

packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts, packages/api-server/src/plugins/services/bot-service/types.ts, packages/api-server/src/routes/healthy/index.ts
=> config: change ai model to GPT_3_5_TURBO_0613

packages/api-server/src/routes/healthy/index.ts
=> fix: fix healthy api bug

packages/api-server/src/routes/healthy/index.ts
=> healthy: check the data latency instead of prefetch request

packages/api-server/src/app.ts, packages/api-server/src/plugins/config/embedding-context-provider.ts, packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/playground-service/index.ts, packages/api-server/src/plugins/services/repo-service/index.ts, packages/api-server/src/plugins/services/user-service/index.ts, packages/api-server/src/routes/bot/questionToSQL/index.ts, packages/api-server/src/routes/bot/questionToSQL/quota/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/chart/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/feedback/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/recommend/cancel/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/recommend/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/summary/index.ts, packages/api-server/src/routes/explorer/questions/_questionId/tags/index.ts, packages/api-server/src/routes/explorer/questions/index.ts, packages/api-server/src/routes/explorer/questions/recommend/batchRefresh/index.ts, packages/api-server/src/routes/explorer/questions/recommend/generate/index.ts, packages/api-server/src/utils/db.ts, packages/api-server/src/utils/error.ts
=> api-server: try to fix the resolve lock timeout error

configs/queries/live-time-top-repos-by-prs-daily/template.sql, packages/api-server/src/scripts/prefetch/index.ts
=> fix: avoid bad plan for prs-daily query

configs/queries/events-total/params.json, configs/queries/live-time-base-information-hourly/params.json, configs/queries/live-time-top-developers-by-prs-daily/template.sql, configs/queries/live-time-top-repos-by-prs-daily/template.sql, packages/api-server/src/core/executor/query-executor/TiDBQueryExecutor.ts, packages/api-server/src/scripts/prefetch/JobScheduler.ts, packages/api-server/src/scripts/prefetch/index.ts
=> prefetch: avoid queue blocking

configs/queries/live-time-top-repos-by-prs-daily/template.sql
=> fix: add hints back

configs/queries/live-time-base-information-hourly/params.json, configs/queries/live-time-base-information-hourly/template.sql, configs/queries/live-time-top-developers-by-prs-daily/params.json, configs/queries/live-time-top-developers-by-prs-daily/template.sql, configs/queries/live-time-top-repos-by-prs-daily/params.json, configs/queries/live-time-top-repos-by-prs-daily/template.sql
=> query: improve live time query

configs/queries/live-time-top-developers-by-prs-daily/params.json, configs/queries/live-time-top-repos-by-prs-daily/params.json
=> query: fix cron

configs/queries/trending-repos/template.sql
=> query: add hints for trending repos query

packages/prefetch/src/index.ts, packages/sync-github-data/.gitignore
=> prefetch: fix params

packages/api-server/src/plugins/services/collection-service/index.ts
=> collection-service: cache colllection-list query for a few time

packages/api-server/src/core/executor/octokit-executor/GhExecutor.ts, packages/api-server/src/plugins/services/bot-service/index.ts
=> api-server: fix the time measure of third party APIs

packages/api-server/src/plugins/services/bot-service/index.ts
=> bot-service: fix deps

packages/api-server/src/core/cache/Cache.ts, packages/api-server/src/core/cache/CacheBuilder.ts, packages/api-server/src/core/cache/provider/NormalTableCacheProvider.ts, packages/api-server/src/plugins/metrics.ts, packages/api-server/src/plugins/services/bot-service/index.ts, packages/api-server/src/routes/healthy/index.ts, packages/prefetch/src/job/scheduler.ts
=> api-server: add cache op timeout

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts
=> refactor: simpify the explorer query timeout

packages/sync-github-data/package.json, packages/sync-github-data/src/commands/users/sync-in-batch.ts, pnpm-lock.yaml
Using `option` instead of `requireOption` method for commander.
=> sync-github-data: fix sync users can not desc problem

packages/api-server/src/core/db/pool-decorator.ts
=> api-server: remove redundant connections already initialized log

configs/queries/collection-issues-history-rank/params.json, configs/queries/collection-issues-history/params.json, configs/queries/collection-issues-last-28-days-rank/params.json, configs/queries/collection-issues-month-rank/params.json, configs/queries/collection-pull-request-creators-history-rank/params.json, configs/queries/collection-pull-request-creators-history/params.json, configs/queries/collection-pull-requests-history-rank/params.json, configs/queries/collection-pull-requests-history/params.json, configs/queries/collection-pull-requests-last-28-days-rank/params.json, configs/queries/collection-pull-requests-month-rank/params.json, configs/queries/collection-stars-history-rank/params.json, configs/queries/collection-stars-history/params.json, configs/queries/collection-stars-last-28-days-rank/params.json, configs/queries/collection-stars-month-rank/params.json, packages/api-server/src/app.ts, packages/api-server/src/core/cache/CacheBuilder.ts, packages/api-server/src/core/runner/query/QueryRunner.ts, packages/api-server/src/env.ts, packages/api-server/src/plugins/cache/cache-builder.ts, packages/prefetch/src/env.ts, packages/prefetch/src/index.ts, packages/prefetch/src/job/scheduler.ts
=> prefetch: fix collection queries no prefetch problem

web/docusaurus.config.js
=> config: update address

packages/api-server/src/plugins/services/tidb-data-service/index.ts, packages/api-server/src/routes/public/index.ts, packages/api-server/src/routes/public/repos/_owner/_repo/index.ts
=> public-api: map path parameters to query string

packages/api-server/README.md, packages/api-server/src/core/runner/query/QueryRunner.ts, packages/api-server/src/env.ts
=> api-server: avoid error when explain onlyFromCache query

packages/api-server/src/core/runner/query/QueryLoader.ts
test:
GET http://localhost:3450/q/events 404 (Not Found)
```json
{
"message": "The config file of query <events> can not be found."
}
```
=> api-server: refine query not found error

configs/queries/trending-repos/params.json, configs/queries/trending-repos/template.sql, packages/api-server/schema/query.schema.json, packages/api-server/src/core/runner/query/QueryParser.ts, packages/api-server/src/core/runner/query/QueryRunner.ts, packages/api-server/src/plugins/runner/query/index.ts, packages/api-server/src/types/query.schema.d.ts, packages/prefetch/src/index.ts, packages/prefetch/src/job/executor.ts, packages/prefetch/src/job/scheduler.ts, pnpm-lock.yaml
=> prefetch: support persist query result to table

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/plugins/services/explorer-service/types.ts, packages/job-server/package.json, pnpm-lock.yaml
=> data-explorer: add sql plan field

etl/meta/collections/10040.api-tool-for-developer.yml
Adds https://github.com/requestly/requestly to collection 10040 (API tools for developers)
=> config: add requestly/requestly repo to collection 10040 (API tools for developers)

etl/meta/collections/10082.web-scanner.yml
=> ETL: add web scanner collection

packages/api-server/src/core/cache/Cache.ts, packages/api-server/src/core/cache/provider/NormalTableCacheProvider.ts
=> cache: refine cache timeout

configs/queries/analyze-issue-creators-map/params.json, configs/queries/analyze-issue-creators-map/template.sql, configs/queries/analyze-pull-request-creators-map/params.json, configs/queries/analyze-pull-request-creators-map/template.sql
=> queries: add prefix for map API

etl/meta/collections/10068.x-as-code.yml
config: add the KCL language project into the open-source XaC collection
=> config: add the KCL language project into the open-source XaC collection

packages/api-server/package.json, packages/api-server/src/plugins/stats/api-request-recorder.ts, pnpm-lock.yaml
=> stats: get real client IP

etl/meta/collections/10024.programming-language.yml
config: add the KCL language project into the open-source programming language collection
=> config: add the KCL language project into the open-source programming language collection

web/sidebars.js
=> public-api: add custom sidebar

etl/meta/collections/10024.programming-language.yml
=> ETL: add wa-lang/wa

etl/meta/collections/10083.programming-language-china.yml, etl/meta/collections/10083.programming-language-of-china.yml
=> add china programming language collection

configs/queries/collection-issues-last-28-days-rank/template.sql, configs/queries/collection-issues-month-rank/template.sql, configs/queries/collection-pull-requests-last-28-days-rank/template.sql, configs/queries/collection-pull-requests-month-rank/template.sql, configs/queries/collection-stars-last-28-days-rank/template.sql, configs/queries/collection-stars-month-rank/template.sql
=> queries: remove use index hint

packages/api-server/src/plugins/services/github-service/index.ts
=> api: returns a defaultBranchRef field from /gh/repos/search api

configs/allowed-origins.yaml
=> config: allow ossinsight-next vercel preview origins

web/docusaurus.config.js
=> web: prevent opening new tab when click widget

etl/meta/collections/10013.game-engine.yml
Hi,
I just wanted to have more information about this nice project and it was missing from this collection. So I just thought I would add it.
Thanks
=> config: add g3n/engine to the game engine collection

configs/search/recommend/orgs/list.json, packages/api-server/src/plugins/services/github-service/index.ts, packages/api-server/src/routes/gh/organizations/search/index.ts
Add Org search API: `/gh/organizations/search?keyword=recommend-org-list-keyword`
For repo search in specify org, we can use API `/gh/repos/search?keyword=tidb owner:pingcap`
=> feat: add org search API

configs/queries/orgs/stars/locations/params.json, configs/queries/orgs/stars/locations/template.sql, configs/queries/orgs/stars/organizations/params.json, configs/queries/orgs/stars/organizations/template.sql, configs/queries/orgs/stars/top-repos/params.json, configs/queries/orgs/stars/top-repos/template.sql, configs/queries/orgs/stars/total/params.json, configs/queries/orgs/stars/total/template.sql, configs/queries/orgs/stars/trends/params.json, configs/queries/orgs/stars/trends/template.sql
Stars Overview:
- `/q/orgs/stars/total?ownerId=11855343`
- `/q/orgs/stars/trends?ownerId=11855343`
Stars Section:
- `/q/orgs/stars/total?ownerId=11855343`
- `/q/orgs/stars/trends?ownerId=11855343`
- `/q/orgs/stars/top-repos?ownerId=11855343`
- `/q/orgs/stars/organizations?ownerId=11855343`
- `/q/orgs/stars/locations?ownerId=11855343` (Note: country_code: `UND` means undefined / unknown)
=> queries: add org stars API

configs/queries/orgs/participants/active/ranking/params.json, configs/queries/orgs/participants/active/ranking/template.sql, configs/queries/orgs/participants/active/total/params.json, configs/queries/orgs/participants/active/total/template.sql, configs/queries/orgs/participants/engagements/params.json, configs/queries/orgs/participants/engagements/template.sql, configs/queries/orgs/participants/locations/params.json, configs/queries/orgs/participants/locations/template.sql, configs/queries/orgs/participants/new/ranking/params.json, configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/params.json, configs/queries/orgs/participants/new/total/template.sql, configs/queries/orgs/participants/organizations/params.json, configs/queries/orgs/participants/organizations/template.sql, configs/queries/orgs/participants/roles/params.json, configs/queries/orgs/participants/roles/template.sql, configs/queries/orgs/participants/trends/params.json, configs/queries/orgs/participants/trends/template.sql
Participants Overview:
- `/q/orgs/participants/active/total?ownerId=11855343`
- `/q/orgs/participants/active/ranking?ownerId=11855343&period=past_90_days`
- `/q/orgs/participants/new/total?ownerId=11855343&period=past_12_months`
- `/q/orgs/participants/new/ranking?ownerId=11855343&period=past_12_months`
Participants Section:
- `/q/orgs/participants/trends?ownerId=6154722&period=past_12_months`
- `/q/orgs/participants/roles?ownerId=6154722&role=commit_authors&period=past_28_days`
- `/q/orgs/participants/engagements?ownerId=6154722&period=past_12_months`
- `/q/orgs/participants/locations?ownerId=6154722&period=past_12_months`
- `/q/orgs/participants/organizations?ownerId=6154722&period=past_12_months`
=> queries: add org participants queries

configs/queries/orgs/reviews/open-to-first-review-duration/medium/params.json, configs/queries/orgs/reviews/open-to-first-review-duration/medium/template.sql, configs/queries/orgs/reviews/open-to-first-review-duration/top-repos/params.json, configs/queries/orgs/reviews/open-to-first-review-duration/top-repos/template.sql, configs/queries/orgs/reviews/review-comments/top-repos/params.json, configs/queries/orgs/reviews/review-comments/top-repos/template.sql, configs/queries/orgs/reviews/review-prs/trends/params.json, configs/queries/orgs/reviews/review-prs/trends/template.sql, configs/queries/orgs/reviews/reviewed-ratio/params.json, configs/queries/orgs/reviews/reviewed-ratio/template.sql, configs/queries/orgs/reviews/total/params.json, configs/queries/orgs/reviews/total/template.sql, configs/queries/orgs/reviews/trends/params.json, configs/queries/orgs/reviews/trends/template.sql
=> queries: add pr reviews queries

packages/prefetch/src/index.ts
=> fix: fix prefetch query runner args

configs/queries/orgs/commits/code-changes/top-repos/params.json, configs/queries/orgs/commits/code-changes/top-repos/template.sql, configs/queries/orgs/commits/time-distribution/params.json, configs/queries/orgs/commits/time-distribution/template.sql, configs/queries/orgs/commits/total/params.json, configs/queries/orgs/commits/total/template.sql, configs/queries/orgs/commits/trends/params.json, configs/queries/orgs/commits/trends/template.sql
Commit Section:
- `/q/orgs/commits/total?ownerId=11855343`
- `/q/orgs/commits/trends?ownerId=11855343`
- `/q/orgs/commits/time-distribution?ownerId=11855343`
- `/q/orgs/commits/code-changes/top-repos?ownerId=11855343`
=> queries: add org commits queries

etl/meta/collections/10024.programming-language.yml, etl/meta/collections/10068.x-as-code.yml
=> Adding OpenTF

configs/queries/orgs/issues/closed-ratio/template.sql, configs/queries/orgs/overview/params.json, configs/queries/orgs/overview/template.sql, configs/queries/orgs/participants/engagements/template.sql, configs/queries/orgs/repos/active/ranking/params.json, configs/queries/orgs/repos/active/ranking/template.sql, configs/queries/orgs/repos/active/total/params.json, configs/queries/orgs/repos/active/total/template.sql
Header:
- `/q/orgs/overview?ownerId=6154722`
Overview:
- `/q/orgs/repos/active/total?ownerId=6154722`
- `/q/orgs/repos/active/ranking?ownerId=6154722`
=> queries: add org repos queries

configs/queries/orgs/stars/organizations/template.sql
=> queries: remove typo

etl/meta/collections/10084.ml-in-rust.yml
Add new collection for machine learning libraries in Rust
=> Add new collection for machine learning libraries in Rust

web/blog/explore-deep-in-4.6-billion-github-events/index.md, web/blog/github-data-is-booming/index.mdx, web/docs/about.md, web/docusaurus.config.js, web/src/pages/home/_sections/0-summary/left/FooterLine.tsx
=> config: change the english website url

web/src/api/core.ts, web/src/api/gh.ts
=> web: use gh api to get user info

etl/meta/collections/10054.monitoring-tool.yml
Add [Alaz eBPF Agent](https://github.com/ddosify/alaz) for Ddosify Platform to Monitoring collection
=> Add Alaz eBPF Agent for Ddosify Platform

configs/queries/archive/2021/company-ranking-by-contributors/params.json, configs/queries/archive/2021/repo-ranking-by-issue-creators/template.sql, configs/queries/archive/2021/repo-ranking-by-issues/template.sql, configs/queries/archive/2021/repo-ranking-by-prs/template.sql, configs/queries/archive/2021/repo-ranking-by-stars-growth/template.sql, configs/queries/orgs/participants/locations/template.sql, configs/queries/orgs/participants/organizations/template.sql, configs/queries/orgs/repos/active/ranking/template.sql, configs/queries/orgs/reviews/open-to-first-review-duration/top-repos/template.sql, configs/queries/orgs/stars/organizations/template.sql, packages/api-server/README.md
=> queries: fix org queries synax error

configs/pipelines/format_org_names/config.json, configs/pipelines/format_org_names/process.sql, packages/pipeline/src/routes/pipelines/_name/full_sync/index.ts
=> pipeline: add format org names pipeline

configs/queries/orgs/participants/organizations/filled-ratio/template.sql, configs/queries/orgs/participants/organizations/template.sql, configs/queries/orgs/stars/organizations/filled-ratio/template.sql, configs/queries/orgs/stars/organizations/template.sql
=> queries: using org formatted column for org queries

configs/queries/analyze-issue-creators-company/params.json, configs/queries/analyze-issue-creators-company/template.sql, configs/queries/analyze-pull-request-creators-company/params.json, configs/queries/analyze-pull-request-creators-company/template.sql, configs/queries/analyze-stars-company/params.json, configs/queries/analyze-stars-company/template.sql, configs/queries/orgs/stars/organizations/filled-ratio/template.sql, packages/api-server/__tests__/helpers/queries.ts, packages/api-server/src/core/runner/query/QueryLiquidParser.ts, packages/types/schema/query.schema.json, packages/types/src/query.schema.d.ts
=> queries: using org formatted column in repo analyze

configs/queries/analyze-recent-collaborative-productivity-metrics/template.sql
=> queries: fix analyze-recent-collaborative-productivity-metrics query

configs/pipelines/format_org_names/config.json, configs/pipelines/sync_org_repo_participants/config.json, configs/pipelines/sync_org_repo_participants/process.sql, configs/pipelines/sync_org_repos/config.json, configs/pipelines/sync_org_repos/process.sql, configs/pipelines/sync_repo_issue_creators/config.json, configs/pipelines/sync_repo_pull_request_creators/config.json, configs/queries/orgs/overview/template.sql, packages/pipeline/src/plugins/pipelines/index.ts, packages/pipeline/src/routes/pipelines/_name/full_sync/index.ts
- Support incremental updates of different granularity on the pipeline
- Use TiFlash for pre aggregation and store the pre aggregated data in TiKV storage.
- Add `sync_org_repos` and `sync_org_repo_participants` pipelines.
=> pipeline: add sync org pre-agg pipeline

packages/prefetch/src/job/scheduler.ts
=> prefetch: inc timeout for long time job

configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/template.sql
=> queries: ⚡ accelerating new participant-related quiries

configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/template.sql
=> queries: simpify new participant queries

configs/queries/orgs/overview/template.sql, configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/template.sql
=> queries: fix new participants query

configs/materialized_views/mv_repo_daily_engagements/ddl.sql, configs/pipelines/sync_org_repo_daily_engagements/process.sql
=> pipeline: rename mv_repo_daily_engagements to mv_repo_daily_engagements_new

configs/materialized_views/mv_repo_daily_engagements/ddl.sql, configs/pipelines/sync_org_repo_participants/process.sql, configs/queries/orgs/overview/template.sql, configs/queries/orgs/participants/active/total/template.sql, configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/template.sql
=> queries: using new repo participants mv

packages/api-server/__tests__/migrations/gharchive_dev.mv_repo_daily_engaments-schema.sql, packages/api-server/__tests__/migrations/gharchive_dev.mv_repo_participants-schema.sql, packages/api-server/src/plugins/socket.io/index.ts
=> api-server: remove empty events increment check

packages/sync-github-data/package.json, packages/sync-github-data/src/libs/locator/Locator.ts, pnpm-lock.yaml
=> sync-github-data: using pinyin-pro instead of pinyin

configs/queries/orgs/participants/active/ranking/template.sql, configs/queries/orgs/participants/active/total/template.sql, configs/queries/orgs/participants/active/trends/template.sql, configs/queries/orgs/participants/engagements/template.sql, configs/queries/orgs/participants/locations/template.sql, configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/template.sql, configs/queries/orgs/participants/new/trends/template.sql, configs/queries/orgs/participants/organizations/template.sql, configs/queries/orgs/participants/trends/template.sql
=> queries: add blacklist to exlucde bots users

configs/queries/orgs/repos/params.json, configs/queries/orgs/repos/template.sql, packages/api-server/src/core/runner/query/QueryRunner.ts
=> queries: add list org repos

configs/queries/orgs/participants/new/trends/template.sql
=> queries: improve new participants trends

configs/queries/orgs/participants/new/ranking/template.sql, configs/queries/orgs/participants/new/total/template.sql
=> queries: fix new participant queries

configs/queries/orgs/commits/trends/template.sql, configs/queries/orgs/issues/actions/trends/template.sql, configs/queries/orgs/issues/trends/template.sql, configs/queries/orgs/participants/active/trends/template.sql, configs/queries/orgs/participants/new/trends/template.sql, configs/queries/orgs/participants/trends/template.sql, configs/queries/orgs/pull-requests/actions/trends/template.sql, configs/queries/orgs/pull-requests/trends/template.sql, configs/queries/orgs/reviews/trends/template.sql, configs/queries/orgs/stars/trends/template.sql
=> queries: refine org trends queries

etl/meta/collections/10053.configuration-management-tools.yml
add winglang to 10053.configuration-management-tools.yml
=> add winglang to 10053.configuration-management-tools.yml

configs/pipelines/sync_org_repo_daily_engagements/config.json
=> pipeline: fix the time range of sync_org_repo_daily_engagements

configs/queries/orgs/participants/new/ranking/template.sql
=> queries: exclude owner itself

configs/queries/repos/params.json, configs/queries/repos/template.sql
=> queries: add get repos by id query

etl/meta/collections/10084.open-source-data-catalogs.yml
Add a new collection for open source data catalogs.
=> Add a new collection for open source data catalogs

configs/queries/orgs/participants/new/ranking/template.sql
=> queries: fix the new participant ranking query

etl/meta/collections/10086.reactive-monolith-frameworks.yml
**Collection Title:** Reactive Monolith Frameworks
This commit introduces the "Reactive Monolith Frameworks" collection with the ID 10086. The purpose of this collection is to list and highlight frameworks that provide reactive UI functionalities within a monolithic architecture. Unlike traditional full-stack frameworks, these reactive monolith frameworks specialize in creating highly interactive and dynamic user interfaces without relying on separate API calls from the client side. They handle UI reactivity and state management primarily on the server side, leveraging technologies such as WebSockets for real-time updates. They can be interesting alternatives to Full-stack client-side front-ends such as React/Vue etc. 
The frameworks included in this collection are:
1. **Livewire …
=> Add collection for Reactive Monolith Frameworks (#10086)

etl/meta/collections/10053.configuration-management-tools.yml
=> config: update 10053.configuration-management-tools.yml

etl/meta/collections/10047.terminal.yml
Add oil shell.
Add projects to enhance shells.
zsh: prezto
bash: bash-it and oh-my-bash
fish: oh-my-fish
=> config: update 10047.terminal.yml

etl/meta/collections/10016.search-engine.yml
=> config: update 10016.search-engine.yml

etl/meta/collections/1.static-site-generator.yml
Add vitepress, nextra, and material for mkdocs.
Remove duplicate react-static entry. Already appears in line 17.
=> config: update 1.static-site-generator.yml

etl/meta/collections/10032.message-and-streaming.yml
=> config: update 10032.message-and-streaming.yml

etl/meta/collections/10007.time-series-database.yml
=> config: update 10007.time-series-database.yml

etl/meta/collections/10087.llm-devtools.yml
Create new list for llm dev tools
=> config: add 10087.llm-devtools.yml

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/api-server/src/routes/explorer/questions/new/index.ts
=> feat: add new explorer question API

packages/api-server/src/routes/explorer/answer/index.ts
=> explorer: refine question answer API error handle

packages/api-server/package.json, packages/api-server/src/routes/explorer/answer/index.ts, packages/api-server/src/utils/sqlite.ts, pnpm-lock.yaml
=> explorer: add sqlite format for answer API response

packages/api-server/src/plugins/services/explorer-service/index.ts, packages/job-server/src/jobs/explorer_high_concurrent_queue/index.worker.ts, packages/job-server/src/jobs/explorer_low_concurrent_queue/index.worker.ts
=> data-explorer: kill connection when query timeout

configs/pipelines/calc_collection_visits/config.json, configs/pipelines/calc_collection_visits/process.sql, configs/queries/recent-hot-collections/template.sql, packages/api-server/__tests__/migrations/gharchive_dev.collections-schema.sql
=> pipeline: store collection past month visits

configs/queries/events-increment/params.json
=> queries: using normal table for cache

configs/queries/trending-repos/params.json, configs/queries/trending-repos/template.sql, packages/job-server/src/jobs/explorer_high_concurrent_queue/index.worker.ts, packages/job-server/src/jobs/explorer_low_concurrent_queue/index.worker.ts
=> queries: refine trending repos query

etl/meta/collections/10005.javascript-framework.yml
I added Refine framework to JS frameworks list
=> config: add Refine to JS Frameworks collection

etl/meta/collections/2.open-source-database.yml
adding Qdrant DB to open source databases
=> config: add qdrant/qdrant repo to open source database collection

etl/meta/collections/10054.monitoring-tool.yml
I also sorted this collection in alphabetical order.
=> adds VictoriaMetrics to collections/10054.monitoring-tool.yml

packages/api-server/src/plugins/services/tidb-data-service/index.ts, packages/api-server/src/utils/endpoint.ts
=> public-api: remove pagination logic and transfer-encoding header

etl/meta/collections/10090.go-web-frameworks.yml, etl/meta/collections/10091.go-logging-libraries.yml
Add two collections for Go Web Frameworks and Go Logging Libraries
Issue Number:
closes #1724
closes #1725
=> config: Add Go web frameworks and logging libs

web/docs/api/showcase.md
=> docs: add ChatGH into the showcase list

etl/meta/collections/10015.text-editor.yml
=> config: add lapce/lapce repo to text editor collection

web/docs/api/showcase.md
=> Add ossinsight-x to API showcase

etl/meta/collections/10015.text-editor.yml
=> config: add zed-industries/zed repo to text editor collection

etl/meta/collections/10087.llm-devtools.yml
=> Add Codefuse to LLM Devtools collection.

etl/meta/collections/10052.golang-orm.yml
- added [yaitoo/sqle](https://github.com/yaitoo/sqle) on 10052.golang-orm.yml
=> config: added `yaitoo/sqle` on 10052.golang-orm.yml

etl/meta/collections/10013.game-engine.yml
This PR adds the open source [Flame Engine](https://flame-engine.org/) to the game engine collection.
=> config: Add flame engine to game engine collection

etl/meta/collections/10056.data-integration.yml
Problem Summary: Update apache/incubator-seatunnel to apache/seatunnel because it already is TLP project.
=> config: Update apache/incubator-seatunnel to apache/seatunnel

etl/meta/collections/10092.browser-extension-frameworks
config: Add 10092.browser-extension-frameworks
=> config: Add 10092.browser-extension-frameworks

etl/meta/collections/10025.distributed-file-storage.yml
Add apache/hdfs (maintained in apache/hadoop) and ozone as a distributed file systems.
=> config: add a couple of distributed file storages

etl/meta/collections/10004.web-framework.yml
=> web: add FastAPI web framework

etl/meta/collections/10066.virtual-reality.yml
Adding [StereoKit](https://github.com/StereoKit/StereoKit) to the list of repos in the VR collection. Seems like the right fit :)
=> config: Add StereoKit to VR Collection

etl/meta/collections/10068.x-as-code.yml, web/blog/how-it-works/index.md, web/blog/reduce-query-latency/index.mdx, web/blog/say-thanks-to-github-robots/index.mdx, web/blog/try-it-yourself/index.md, web/src/dynamic-pages/analyze-user/sections/2-Star.tsx, web/src/dynamic-pages/analyze/sections/1-People.tsx, web/src/pages/try-your-own-dataset/index.tsx, workshop.cn.ipynb
Problem Summary: Some typos and grammar mistake exist, which affect user experience with OSS Insight.
This PR fixes multiple typos in text (ignoring those in code), and some grammar or format issues.
=> web, etl: fix multiple typos and grammar

etl/meta/collections/10003.low-code-development-tool.yml
Grist is a modern relational spreadsheet. It combines the flexibility of a spreadsheet with the robustness of a database.
=> config: add gristlabs/grist-core to Low Code Development Tools

etl/meta/collections/10094.vector-database.yml
=> collections: add vector store & vector database

etl/meta/collections/10021.api-gateway.yml
This PR does not fix any "problem", but includes Lura (Linux Foundation) and KrakenD API gateway into the API Gateway collection.
Thanks
=> config: add missing gateways to api gateway collection

README.md
Added global community link.
Problem Summary: Nope
Just added global community link to README file.
=> feat: add global community link

etl/lib/importer.rb
=> feat: bulk insert 50000 records

etl/lib/importer.rb
Reverts pingcap/ossinsight#1772
=> Revert "feat: bulk insert 50000 records"

etl/meta/collections/10088.webrtc.yml
Adding a few more projects to the WebRTC collection. Adding comments to label and group projects by type. Sorting alphabetically within the group.
=> config: expand and organize 10088.webrtc.yml

web/src/api/client.ts, web/src/pages/gift/_components/ClaimCredits/index.tsx, web/src/pages/gift/index.tsx
=> test: gift page

etl/lib/importer.rb
=> feat: change bulk insert size to 20000

etl/lib/importer.rb
=> etl: change bulk insert size from 20000 to 90000

etl/meta/collections/10079.stable-diffusion-ecosystem.yml
Add the [LykosAI/StabilityMatrix](https://github.com/LykosAI/StabilityMatrix) project (Multi-Platform Package Manager for Stable Diffusion) to [ossinsight.io/collections/stable-diffusion-ecosystem](https://ossinsight.io/collections/stable-diffusion-ecosystem/)
Issue Number: close #1786
=> collections: Add StabilityMatrix to Stable Diffusion Ecosystem Collection

web/src/pages/open-source-heroes/_sections/6-legal.mdx
=> doc: credits valid duration from 180 days to 1 year

configs/collections/10034.diagram-as-code.yml, configs/collections/10037.hyperledger.yml
This change includes the CNCF Meshery project (https://meshery.io) in the "Diagram as Code" collection.
See the Meshery project website for examples of how it diagrams and manages cloud native infrastructure visually.
=> config: add meshery/meshery repo to "Diagram as Code" collection

configs/collections/10044.modern-data-stack.yml
=> config: add dlt to modern data stack collection

configs/collections/10044.modern-data-stack.yml
Issue Number: N/A
Problem Summary: Adding https://open-metadata.org/ to the MDS list
=> config: add OpenMetadata to Modern Data Stack collection

configs/collections/10008.graph-database.yml
=> config: add FalkorDB/FalkorDB repo to Graph Database collection

configs/collections/10095.graphrag.yml
=> Add GraphRAG repo

configs/collections/10089.relational-database.yml, configs/collections/2.open-source-database.yml
As Cloudberry has entered the ASF Incubator[^1], rename its old repo name to the new one.
[^1]: https://cloudberry.apache.org/blog/cloudberry-database-enters-the-apache-incubator
=> config: rename CloudberryDB to Apache Cloudberry

configs/collections/10077.vector-search-engine.yml, configs/collections/10094.vector-database.yml
=> collection: add Epsilla to vector db collection

configs/collections/10004.web-framework.yml, configs/collections/10005.javascript-framework.yml, configs/collections/10008.graph-database.yml, configs/collections/10010.artificial-intelligence.yml, configs/collections/10011.artificial-intelligence-of-china.yml, configs/collections/10015.text-editor.yml, configs/collections/10018.apm-tool.yml, configs/collections/10033.identity-server.yml, configs/collections/10037.hyperledger.yml, configs/collections/10038.hyperledger-besu.yml, configs/collections/10043.go-database.yml, configs/collections/10047.terminal.yml, configs/collections/10048.ui-framework-and-uikit.yml, configs/collections/10050.open-source-forum-software.yml, configs/collections/10051.security-tool.yml, configs/collections/10058.mlops-tools.yml, configs/collections/10059.key-value-database.yml, configs/collections/10075.chatgpt-alternatives.yml, configs/collections/10078.chatgpt-apps.yml, configs/collections/10087.llm-devtools.yml
=> collection: fix the collection config

configs/collections/10063.kubernetes-tooling.yml
config: add meshery/meshery repo to "Kubernetes Tooling" collection
=> config: add meshery/meshery repo to "Kubernetes Tooling" collection

configs/collections/10045.tui-framework.yml
Problem Summary: The popular Rust ratatui framework was missing from the TUI Frameworks collection. This PR adds it.
=> config: Add Rust ratatui framework to TUI collection

configs/collections/10051.security-tool.yml
add intuitem/ciso-assistant-community to security collection
=> config: add ciso-assistant to security collection

configs/collections/10097.ai-training-tracking.yml
A collection of open-source AI training tracking and visualization tool, and it can help to observe the model training process.
=> config: add new collection about ai training observability

configs/collections/10005.javascript-framework.yml, configs/collections/10076.llm-tools.yml, configs/collections/10098.ai-agent-frameworks.yml
I added new collection of "AI Agent Frameworks".
Also, I added open-source Voltagent  framework to LLMtools and Javascript frameworks list.
=> config: add new collection about ai agent frameworks

configs/collections/10051.security-tool.yml
Add the https://github.com/safedep/vet project to https://ossinsight.io/collections/security-tool
Issue Number: close #1845
=> config: add safedep/vet repo to security tool collection
