- src/components/github/Owner/index.tsx
另外一个问题是，现在使用的avatar url是 https://github.com/{repo_name}.png
比如：https://github.com/Trenly.png
这种格式的url会在前端经过一次302跳转到 https://avatars.githubusercontent.com/u/12611259?v=4
如果在API接口查出org_id，给前端返回 `/u/12611259?size=20` 这种格式url会更快一些
> use small avatar

- docs/language/01-deep-insight-into-programming-languages-2021.mdx
The graph of "Top 20 developers contributed the most PRs to PL repos in 2021" was put in the wrong place so I replaced the title.
It seems there is no sql about “Top 10 PL repos with the most contributors in 2021” here, so I deleted it.
> docs: fix the error in the display order

- docusaurus.config.js
replace GA4 id with GTM id
https://tagmanager.google.com/?hl=zh-CN_cn#/container/accounts/6006808381/containers/66687760/workspaces/3
> Update GTM id

- blog/explore-deep-in-4.6-billion-github-events/index.md
- blog/how-it-works/index.md
- blog/saas-insight-for-building-a-real-time-crm-application.md
- blog/try-it-yourself/index.md
- blog/why-we-choose-tidb-to-support-oss-insight/index.md
Since we have a new website for quick signup, it is better than we replace https://tidbcloud.com/signup with https://tidbcloud.com/free-trial in the URL.
> update URL of TiDB Cloud free trial

- backend/meta/collections/10030.finance.yml
Hey 👋🏽 
I am the creator behind [OpenBB-finance/OpenBBTerminal](OpenBB-finance/OpenBBTerminal) and thought it would be nice for you to have a finance topic for your collections.
I selected the projects based on the number of stars when searching for `finance` tag, see https://github.com/search?o=desc&p=1&q=finance&s=stars&type=Repositories
I didn't add some of the projects because I didn't really consider them "finance", for instance:
* a repository that just contains a list of nice finance resources.
* a plotting library that can be used to plot historical data.
Feel free to add more packages if you think that some are missing, or to remove some if you don't think they should be there.
> Add finance collection

- backend/meta/collections/10010.artificial-intelligence.yml
PyTorch Lightning is one of the most popular repos in ML that is missing from the list for AI
> Add PyTorch lightning to 10010.artificial-intelligence.yml

- api/queries/personal-overview/template.sql
> NOT IN returns 0 records when compared against an unknown value
> Since NULL is an unknown, a NOT IN query containing a NULL or NULLs in the list of possible values will always return 0 records since there is no way to be sure that the NULL value is not the value being tested.
https://stackoverflow.com/a/129151
> fix: fix contribute to repos be zero problem

- api/queries/get-user-by-login/template.sql
Some GitHub users may register multiple accounts one after another but use the same login.
```
gharchive_dev> SELECT
->     DISTINCT actor_id AS id, 'PsiACE' AS login
-> FROM github_events
-> WHERE
->     actor_login = 'PsiACE'
->     AND actor_id IS NOT NULL
-> ;
+----------+--------+
| id       | login  |
+----------+--------+
| 36896360 | PsiACE |
| 25458566 | PsiACE |
| 25342314 | PsiACE |
+----------+--------+
3 rows in set
Time: 0.115s
```
> fix: get user id by login should get the latest one

- api/queries/analyze-recent-commits/params.json
- api/queries/analyze-recent-commits/template.sql
- api/queries/analyze-recent-issues/params.json
- api/queries/analyze-recent-issues/template.sql
- api/queries/analyze-recent-pull-requests/params.json
- api/queries/analyze-recent-pull-requests/template.sql
- api/queries/analyze-recent-stars/params.json
- api/queries/analyze-recent-stars/template.sql
- api/queries/analyze-recent-top-contributors/params.json
- api/queries/analyze-recent-top-contributors/template.sql
- api/queries/analyze-stars-map/params.json
- api/queries/analyze-stars-map/template.sql
- analyze-recent-commits
- analyze-recent-pull-requests
- analyze-recent-issues
- analyze-recent-stars
- analyze-recent-top-contributors
- analyze-stars-map (we can replace `stars-map` with it, provide [period](https://github.com/pingcap/ossinsight/blob/fbffee1fe3dd5a3b5f15b1b5eeb88da15ac55095/api/queries/analyze-stars-map/params.json) params)
> feat(sql): add repo last 28 days queries

- api/queries/analyze-loc-per-month/template.sql
- api/queries/analyze-pull-requests-size-per-month/template.sql
- api/queries/analyze-pushes-and-commits-per-month/template.sql
- api/queries/commits-time-distribution/params.json
- api/queries/commits-time-distribution/template.sql
Use `created_at` instead of `event_month` now, it will use index automatically when the `add index` task finish.
on (repo_id, type, action, created_at, push_distinct_size, push_size)
on (repo_id, type, action, pr_merged, created_at, additions, deletions)
Close #732 #733
> sql: use `created_at` instead of `event_month`

- backend/meta/collections/10051.security-tool.yml
Add OWASP dependency-check - a widely used SCA tool.
> Add OWASP dependency-check

- api/app/core/BatchLoader.ts
- api/app/core/cache/CacheBuilder.ts
- api/app/core/cache/CacheProvider.ts
- api/app/core/cache/CachedTableCacheProvider.ts
- api/app/core/cache/NormalTableCacheProvider.ts
- api/app/utils/db.ts
- api/scripts/cache-gc/index.ts
- api/scripts/calc-hot-collections/index.ts
- api/scripts/sync-nginx-log/index.ts
- api/scripts/sync-repos/worker.ts
- api/scripts/sync-users/index.ts
Some components of the API-Server use a single database connection. If the client disconnected with the database server, the service will be unavailable and throw the following errors in the program.
```
Error: Connection lost: The server closed the connection.
at Socket.<anonymous> (xxx/ossinsight/api/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:101:31)
at Socket.emit (node:events:527:28)
at TCP.<anonymous> (node:net:709:12)
Emitted 'error' event on Connection instance at:
at Connection._notifyError (xxx/ossinsight/api/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:236:12)
at Socket.<anonymous> (xxxx/ossinsight/api/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/lib/connection.js:107:12)
at Socket.emit (node:events:527:28)
at …
```
> fix: handle mysql/tidb server connection lost

- backend/meta/collections/10043.go-database.yml
- backend/meta/collections/2.open-source-database.yml
Add milvus in opensource and go-database category.
> add milvus in opensource and go-database

- docker-compose.yml
- etl/Gemfile
- etl/Gemfile.lock
part of #970
0.5.3 doesn't support tls when working with mariadb client which is the case in docker image.
See issue here: https://github.com/brianmario/mysql2/issues/1094
Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>
> Upgrade mysql2 to support ssl_mode

- etl/meta/collections/10068.x-as-code.yml
Add an `X as Code` collection to OSS Insight.
The relationship between `X as Code` and `Configuration management` tools is the following:
1. The `X as Code` is a subset of `Configuration Management`.
2. `X as Code` uses declarative API to interact with X. X such as the **Infrastructure**, **Application**, **Database**, etc.
> config: add `X as Code` collection

- etl/meta/collections/10051.security-tool.yml
This PR adds VAST to the security tool list.
> collection: add VAST to security tool collection

- packages/api-server/src/core/playground/playground.ts
https://github.com/pingcap/ossinsight/discussions/1024#discussioncomment-4372951
Only check where clause when the SQL select from `github_events` table.
> playground: fix the where clause checker

- packages/api-server/src/plugins/services/bot-service/template/GenerateAnswerPromptTemplate.ts
Wrong:
```sql
select repo_name from github_events ge inner join github_repos gr ....
```
Correct:
```sql
select ge.repo_name from github_events ge inner join github_repos gr ....
```
> ai(prompt): prompt ai to set table name as prefix to avoid ambiguous column name

- etl/meta/collections/10070.Approximate-Nearest-Neighbor-library.yml
This pr is to add a new collection of approximate nearest neighbor library on Github, which can be used to search approximate nearest neighbor of high dimension vector in many areas.
I found ossinsight collection have no such an entry and organize the collection based on [ann-benchmark](https://github.com/erikbern/ann-benchmarks) that contains some tools to benchmark various implementations of approximate nearest neighbor (ANN) search for different metrics.
> ETL: add approximate nearest neighbor library collection

- api/package.json
- packages/api-server/src/plugins/config/prompt-template-manager.ts
> All variables are HTML-escaped by default. If you want to render unescaped HTML, use the triple mustache: {{{name}}}. You can also use & to unescape a variable.
> 
> If you'd like to change HTML-escaping behavior globally (for example, to template non-HTML formats), you can override Mustache's escape function. For example, to disable all escaping: Mustache.escape = function(text) {return text;};.
> 
https://github.com/janl/mustache.js#variables
> prompt-manager: do not escape for prompt template

- packages/api-server/src/plugins/services/bot-service/index.ts
> explorer: remove table name for chart options

- etl/meta/collections/10005.javascript-framework.yml
Adds qwik framework to the list of javascript frameworks!
In the same repo, we also have QwikCity the equivalent to SvelteKit, or Solid Start, or Next, can I add the same repo to several sections?
> config: Add Qwik to Javascript frameworks

- etl/meta/collections/10072.business-management.yml
This PR adds the repository calcom/cal.com to the business-management collection.
> etl: added calcom/cal.com to business-management collection

- packages/api-server/src/plugins/services/bot-service/index.ts
- packages/api-server/src/plugins/services/explorer-service/index.ts
- packages/api-server/src/utils/sleep.ts
Handle the following error when the data explorer access OpenAI API, and add retry logic for it
> aborted
> Request failed with status code 429
> The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined
> explorer: add retry logic for openai API

- etl/meta/collections/10068.x-as-code.yml
Meshery falls into the X as Code in terms of the designs/patterns it uses to manage infrastructure. See the emerging https://meshery.io/catalog for example designs/patterns.
> Add meshery/meshery to the X as Code sub-category

- etl/meta/collections/10063.kubernetes-tooling.yml
Helm-Dashboard is one of the most popular new OSS K8s repos
> config: add komodorio/helm-dashboard repo to open source database collection

- package.json
- packages/api-server/package.json
- packages/api-server/src/plugins/services/explorer-service/index.ts
- packages/api-server/src/plugins/services/explorer-service/types.ts
- packages/api-server/src/routes/explorer/questions/index.ts
- packages/api-server/src/routes/explorer/questions/recommend/batchRefresh/index.ts
- pnpm-lock.yaml
Re-execute the recommended question in batch. After re-execution, it needs to be manually approved to reset it as a recommended question. (Because the result of AI returns is not stable, it is necessary to manually confirm whether the result after re-execution is still satisfactory.)
To get the questions need to review, can execute the following SQL:
```sql
SELECT batch_job_id, CONCAT('https://ossinsight.io/explore/?id=', BIN_TO_UUID(eq.id)) AS link, user_id, title, status, error_type, eq.created_at, GROUP_CONCAT(eqt.label) AS labels, answer
FROM explorer_questions eq
LEFT JOIN explorer_question_tag_rel eqtr ON eq.id = eqtr.question_id
LEFT JOIN explorer_question_tags eqt ON eqt.id = eqtr.tag_id
WHERE
recommended = 0
AND need_review = 1
GROUP BY eq.id
ORDER BY created_at DESC
```
In …
> explorer: add trigger batch refresh API

- etl/meta/collections/10063.kubernetes-tooling.yml
Think TCPDump and Wireshark re-invented for Kubernetes, Kubeshark provides protocol-level visibility into Kubernetes’ internal network, capturing, dissecting and monitoring all traffic and payloads going in, out and across containers, pods, nodes and clusters.
> Adding network analysis for Kubernetes

- etl/meta/collections/10042.rust-database.yml
Open source rust databases list was missing influxdata-influxdb_iox repo.
This pull request adds Influxdb IOx to the list of rust databases.
> config: add influxdata/influxdb_iox repo to open source database collection

- etl/meta/collections/10056.data-integration.yml
Cloudquery is an airbyte alternative (open source high performance data integration platform).
https://cloudquery.io/
> config: Add cloudquery/cloudquery to open source data

- web/src/dynamic-pages/analyze-user/Navigator.tsx
It seems to be more relevant in the context of the project to use en-US than en-GB.
---
By the way, we are using the SQL API to create custom metrics for Material UI, it's great :)
App: https://tools-public.onrender.com/prod/pages/9r8fshsf
Source: https://github.com/mui/mui-public/blob/1d5189ff9b50a95a315d5f54269080ef6a57b04c/tools-public/toolpad/queries.ts#L30
> user-analyze: use en-US

- etl/meta/collections/10051.security-tool.yml
Extended the security tool collection adding `slimtoolkit` to it (slimtoolkit can be used to reduce the attack surface in container images, which also reduces the number of vulnerabilities in those container images)
> config: added slim to the security tools collection

- etl/meta/collections/10080.networking-for-games.yml
This is not a complete list. Got some of the items from https://github.com/ThusSpokeNomad/GameNetworkingResources
> Add collection: Networking for Games

- etl/meta/collections/10020.cicd.yml
- etl/meta/collections/10063.kubernetes-tooling.yml
Adding gimlet-io/gimlet to Kubernetes tooling and CICD collections.
> config: Adding gimlet-io/gimlet to kubernetes tooling and cicd collections

- packages/api-server/src/core/db/pool-decorator.ts
- packages/api-server/src/core/executor/query-executor/TiDBPlaygroundQueryExecutor.ts
- packages/api-server/src/plugins/services/explorer-service/index.ts
The `PoolConnection` object is a wrapper of the `Connection` object, and a new `PoolConnection` object is created each time the `getConnection` method is executed. The internal `Connection` object is recycled.
Therefore, it is not valid to set the initialized property on the `PoolConnection`, but to set the `Connection` object inside it.
> api-server: fix the decorator to avoid init playground conn each time

- packages/api-server/src/routes/public/index.ts
> public-api: fix the prefix of public api endpoint

- packages/api-server/src/core/cache/Cache.ts
- packages/api-server/src/core/cache/provider/NormalTableCacheProvider.ts
- packages/api-server/src/routes/q/index.ts
Automatically add [HTTP Expires header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires) to `/q` query response to enable client side caching.
> feat(api): support http expires response header

- .github/workflows/verify-query.yml
- configs/queries/analyze-recent-contributors/params.json
- configs/queries/analyze-recent-contributors/template.sql
- configs/queries/events-increment-list/template.sql
- configs/queries/recent-hot-collections/template.sql
- packages/api-server/package.json
- add analyze recent contributors query
- recent-hot-collections: using stats_api_requests table instead of access_logs
- improve events-increment-list query performance
> queries: add analyze recent contributors query

- configs/queries/orgs/issues/actions/trends/params.json
- configs/queries/orgs/issues/actions/trends/template.sql
- configs/queries/orgs/issues/closed-ratio/params.json
- configs/queries/orgs/issues/closed-ratio/template.sql
- configs/queries/orgs/issues/issue-comments/top-repos/params.json
- configs/queries/orgs/issues/issue-comments/top-repos/template.sql
- configs/queries/orgs/issues/open-to-close-duration/medium/params.json
- configs/queries/orgs/issues/open-to-close-duration/medium/template.sql
- configs/queries/orgs/issues/open-to-close-duration/top-repos/params.json
- configs/queries/orgs/issues/open-to-close-duration/top-repos/template.sql
- configs/queries/orgs/issues/open-to-first-response-duration/medium/params.json
- configs/queries/orgs/issues/open-to-first-response-duration/medium/template.sql
- configs/queries/orgs/issues/open-to-first-response-duration/top-repos/params.json
- configs/queries/orgs/issues/open-to-first-response-duration/top-repos/template.sql
- configs/queries/orgs/issues/total/params.json
- configs/queries/orgs/issues/total/template.sql
- configs/queries/orgs/issues/trends/params.json
- configs/queries/orgs/issues/trends/template.sql
Issues Overview:
- `/q/orgs/issues/total?ownerId=11855343`
- `/q/orgs/issues/trends?ownerId=11855343`
Issues Section:
- `/q/orgs/issues/closed-ratio?ownerId=11855343`
- `/q/orgs/issues/actions/trends?ownerId=11855343`
- `/q/orgs/issues/open-to-first-response-duration/medium?ownerId=11855343`
- `/q/orgs/issues/open-to-first-response-duration/top-repos?ownerId=11855343`
- `/q/orgs/issues/open-to-close-duration/medium?ownerId=11855343`
- `/q/orgs/issues/open-to-close-duration/top-repos?ownerId=11855343`
- `/q/orgs/issues/issue-comments/top-repos?ownerId=11855343`
> queries: add org issues queries

- configs/queries/analyze-repo-top-contributors/params.json
- configs/queries/analyze-repo-top-contributors/template.sql
This is same to `analyze-recent-top-contributors` without time restrictions.
> query: add new query `analyze-repo-top-contributors`

- etl/meta/collections/10013.game-engine.yml
Add [Ambient](https://github.com/ambientrun/ambient) to the open source game engines collection
> config: Add ambientrun/ambient to open source game engines collection

- etl/meta/collections/10013.game-engine.yml
Add isadorasophia/murder as part of the "game engines" list.
> config: add isadorasophia/murder to game-engine collection

- etl/meta/collections/10013.game-engine.yml
Added HaxeFlixel
HaxeFlixel is a popular 2D OSS game engine with over 1.8K stars, and seems like it should be on the list:
https://github.com/HaxeFlixel/flixel
> config: added HaxeFlixel to list of game engines

- etl/meta/collections/10013.game-engine.yml
It seems like Ambient is still not showing up in the game engine list, so figured it might be case sensitive.
> config: Fix ambientrun/ambient case

- packages/api-server/src/plugins/services/explorer-service/index.ts
- packages/api-server/src/plugins/services/explorer-service/types.ts
- web/src/api/explorer.ts
- web/src/pages/explore/_components/SqlSection/ErrorMessage.tsx
Issue Number: close #1530
In this PR, we address the need for more robust error handling within the `Data-explorer` module. Users will now receive an informative error message if their query exceeds the defined length.
> data-explorer: introduce error handling for long questions

- etl/meta/collections/10088.webrtc.yml
Create collection for WebRTC projects ranging from full stack solutions, to media servers, and WebRTC libraries. WebRTC is a niche area so I preferred adding these projects into a single collection rather than breaking them up into separate collections.
This collection is numbered 10088 since there is a pending PR for new collection 10087.
> config: create 10088.webrtc.yml

- etl/meta/collections/10063.kubernetes-tooling.yml
config: add loft-sh/vcluster repo to kubernetes tooling collection
Link: https://github.com/loft-sh/vcluster/
> config: add loft-sh/vcluster repo to kubernetes tooling collection

- etl/meta/collections/10076.llm-tools.yml
adds langfuse repo to llm-tools collection config.
langfuse: https://github.com/langfuse/langfuse/
langfuse is a an open source LLM engineering platform, providing observability, prompt management, evals, metrics & playground. it integrates with langchain, llama-index, open ai -- 3k github stars
> config: add langfuse to llm-tools collection

- etl/meta/collections/10004.web-framework.yml
This PR adds the open source framework [Zango](https://zango.dev/) to the web framework collection.
> Add zango to web framework collection

- etl/meta/collections/10013.game-engine.yml
Adding [Cubzh](https://github.com/cubzh/cubzh) to the list of game engines. 🙂
> config: Add Cubzh to game engine collection

- README.md
- web/blog/chat2query-tutorials/index.mdx
- web/blog/explore-deep-in-4.6-billion-github-events/index.md
- web/blog/how-it-works/index.md
- web/blog/saas-insight-for-building-a-real-time-crm-application/index.md
- web/blog/try-it-yourself/index.md
- web/docs/about.md
- web/docs/workshop/ossinsight-lite/setup-tidb-serverless.md
> update tidbcloud utm

- configs/collections/10061.slack-alternative.yml
Add hcengineering/platform (Huly Platform) to Slack Alternative collection.
More info about project here: https://huly.io
Repo: https://github.com/hcengineering/platform
> config: add hcengineering/platform to slack alternative collection

- configs/collections/10096.project-management.yml
Add project management collection (10096), repos included:
- AppFlowy-IO/AppFlowy
- makeplane/plane
- mattermost-community/focalboard
- frappe/erpnext
- hcengineering/platform
- opf/openproject
- kanboard/kanboard
- kuaifan/dootask
- Leantime/leantime
- JordanKnott/taskcafe
> config: add project management collection (10096)

- configs/collections/10013.game-engine.yml
Adds a new game engine/framework to the game engine collection.
> config: add kinsondigital/velaptor repo to game engine collection

- configs/collections/10015.text-editor.yml
- configs/collections/10037.hyperledger.yml
Add following repo:
Stars and last update time at 2024-10-25
- [dail8859/NotepadNext][]: 9.1k star, Updated 16 days ago
- [cxasm/notepad--]: 6.2k star, Updated 7 days ago
- [rizonesoft/Notepad3]: 5.1k star, Updated 10 days ago
- [zufuliu/notepad4]: 3.3k star, Updated 21 hours ago
[dail8859/NotepadNext]: https://github.com/dail8859/NotepadNext
[cxasm/notepad--]: https://github.com/cxasm/notepad--
[rizonesoft/Notepad3]: https://github.com/rizonesoft/Notepad3
[zufuliu/notepad4]:https://github.com/zufuliu/notepad4
> config: add Notepad like repos to text-editor collection

- configs/collections/10012.headless-cms.yml
Adding tyzo to the headless CMS collection
> config: Add tyzo repo to headless CMS collection

- configs/collections/10040.api-tool-for-developer.yml
Adds keploy's repository to https://ossinsight.io/collections/api-tool-for-developer/
Issue Number: close #1830 
Added Keploy's repository ( ) to the api tools for developers collection at https://ossinsight.io/collections/api-tool-for-developer/
Changed the following file to add keploy to the collection: https://github.com/pingcap/ossinsight/blob/main/configs/collections/10040.api-tool-for-developer.yml
> config: add keploy/keploy repo to api tools for developers collection

- configs/collections/10008.graph-database.yml
[Kuzu](https://github.com/kuzudb/kuzu) is an open source,  embedded graph database that's been gaining in popularity, and we have an active user community building production applications. We'd much appreciate being included in this list as well. Thank you!
Issue Number: close #1858 
Updated the last line in `10008.graph-database.yml` to point to the Kuzu GitHub repo.
If there's any other place where it needs to be updated to build the site, please let me know. Thanks!
> config: Add Kuzu to the graph database list

- configs/collections/10076.llm-tools.yml
**Category:** `llm-dev-tools`  
**Type:** API Testing and Unit Testing Tool  
**Repository:** [keploy/keploy](https://github.com/keploy/keploy)
**Description:**  
Keploy is an open-source testing toolkit purpose-built for modern API and LLM-based applications. It captures real API calls and automatically generates test cases and mocks—making it ideal for validating LLM agents and pipelines. Keploy helps automate unit testing for LLM agents by recording their external calls (e.g., to language models, vector databases, or tools) and replaying them with mocks, enabling consistent and isolated testing without needing live dependencies.
**Why it’s relevant to LLM Dev Tools:**  
Developers building applications with large language models (LLMs) often work with APIs, pipelines, and inference …
> config: add Keploy to LLM Tools collection
